CREATE TABLE INDIGO_SECURITY 
(
  SECURITY_ID VARCHAR(255) 
, SECURITY_KEY CHAR(32) PRIMARY KEY
, USE_KEY CHAR(1) DEFAULT 'Y'
, CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP  
);

CREATE SEQUENCE CHARGER AS BIGINT START WITH 41 INCREMENT BY 1 MINVALUE 1 NO CYCLE;

CREATE TABLE ROUTE_INFO (
  IF_ID                VARCHAR(64)       NOT NULL,
  DEST_ID              VARCHAR(64)       NOT NULL,
  SND_CD               VARCHAR(30)       NOT NULL, 
  RCV_CD               VARCHAR(30)       NOT NULL, 
  DATA_ARR_QUEUE       VARCHAR(30)       NOT NULL,
  DATA_DEST_QUEUE      VARCHAR(30)       NOT NULL,
  RESULT_ARR_QUEUE     VARCHAR(30)       NOT NULL,
  RESULT_DEST_QUEUE    VARCHAR(30)       NOT NULL,
  REMOTE_YN            VARCHAR(1)        NOT NULL,
  CHANGE_DATE          VARCHAR(17)       NOT NULL,
  DESCRIPTION          VARCHAR(1000)     ,
  USING_IP             VARCHAR(4000)     ,
  USE_YN               CHAR(1)           DEFAULT 'N'
);

/* ROUTE_INFO에 IF_NAME(인터페이스 이름)컬럼 추가 */
ALTER TABLE ROUTE_INFO ADD COLUMN IF_NAME VARCHAR(100);

/* TEMPLATE 테이블 끝 */

CREATE TABLE ESB_DEPLOY_MAPPING(IN_ID VARCHAR(22) NOT NULL,IS_ID VARCHAR(22) NOT NULL,PRIMARY KEY(IN_ID,IS_ID));

CREATE TABLE ESB_HOST(HOST_NAME VARCHAR(50) NOT NULL PRIMARY KEY,HOST_IP VARCHAR(40) NOT NULL,HOST_ORDER INTEGER NOT NULL);

CREATE TABLE ESB_IMANAGER(IM_ID VARCHAR(22) NOT NULL PRIMARY KEY,IM_IP VARCHAR(40) NOT NULL,IM_PORT VARCHAR(5) NOT NULL,IM_OS VARCHAR(100),IM_INFO VARCHAR(1000),IM_VER VARCHAR(20),IM_COMMUNICATION VARCHAR(10) DEFAULT 'http' ,SYSTEM_ID VARCHAR(20) DEFAULT '');

CREATE TABLE ESB_INSTANCE(IN_ID VARCHAR(22) NOT NULL PRIMARY KEY,PJ_ID VARCHAR(22),IN_INFO VARCHAR(1000),IN_DEPLOY_YN VARCHAR(1),IN_DEPLOY_DATE TIMESTAMP,IN_START_XMS VARCHAR(5),IN_START_XMX VARCHAR(5),IN_COMPILER_OPT VARCHAR(500),IN_AUTOSTART_YN VARCHAR(1),IN_AUTOSTART_CNT INTEGER, IN_EXCLUSIVE_CLASSPATH VARCHAR(1024) DEFAULT '', IN_PORT VARCHAR(10) DEFAULT '');
CREATE INDEX XIE1ESB_INSTANCE ON ESB_INSTANCE(PJ_ID);

CREATE TABLE ESB_INSTANCE_FILE(IN_ID VARCHAR(22) NOT NULL,IN_FILE_ID INTEGER NOT NULL,IN_FILE_NAME VARCHAR(100) NOT NULL,IN_FILE_CONTS CLOB, PRIMARY KEY(IN_ID,IN_FILE_ID));

CREATE TABLE ESB_ISERVICE(IS_ID VARCHAR(22) NOT NULL PRIMARY KEY,IS_ORDER INTEGER NOT NULL,IS_FILE_NAME VARCHAR(200) NOT NULL,IS_INFO VARCHAR(1000),IS_USE_VER INTEGER NOT NULL,FO_ID VARCHAR(22) NOT NULL);

CREATE TABLE ESB_ISERVICE_VER(IS_ID VARCHAR(22) NOT NULL,IS_VER INTEGER NOT NULL,IS_REG_USER VARCHAR(50),IS_REG_DATE TIMESTAMP,IS_FILE_SIZE INTEGER,IS_FILE BLOB NOT NULL,IS_INFO VARCHAR(1000) NOT NULL,PRIMARY KEY(IS_ID,IS_VER));

CREATE TABLE ESB_MONITOR(MO_ID VARCHAR(22) NOT NULL PRIMARY KEY,IM_STATUS VARCHAR(2),NW_STATUS VARCHAR(2),DS_STATUS VARCHAR(2),CPU_USE VARCHAR(10),MEMORY_USE VARCHAR(10),CPU_TIME VARCHAR(10),ELAPSED_TIME VARCHAR(20),MO_REG_DATE TIMESTAMP NOT NULL,MO_STATUS VARCHAR(2),PD_ID VARCHAR(22) NOT NULL);
CREATE INDEX XIE1ESB_MONITOR ON ESB_MONITOR(PD_ID);

CREATE TABLE ESB_PRODUCT(PD_ID VARCHAR(22) NOT NULL PRIMARY KEY,PD_TYPE VARCHAR(2),PD_ORDER INTEGER NOT NULL,PD_NAME VARCHAR(100) NOT NULL,PD_ALIAS VARCHAR(100),PD_REG_DATE TIMESTAMP,PD_REG_USER VARCHAR(50),IN_IM_ID VARCHAR(22),FINAL_NW_STATUS VARCHAR(2),FINAL_MO_STATUS VARCHAR(2),FINAL_MO_REG_DATE TIMESTAMP,MO_ERROR_CNT INTEGER NOT NULL, FINAL_DS_STATUS VARCHAR(2) DEFAULT '', PD_FAVORITE varchar(2), PD_FIREWALL char(1), PD_GROUP_ID VARCHAR(20) DEFAULT '', CONSTRAINT SYS_CT_62 UNIQUE(PD_NAME));
CREATE INDEX XIE1ESB_PRODUCT ON ESB_PRODUCT(IN_IM_ID);

CREATE TABLE ESB_PROJECT(PJ_ID VARCHAR(22) NOT NULL PRIMARY KEY,PJ_ORDER INTEGER NOT NULL,PJ_NAME VARCHAR(50) NOT NULL,PJ_REG_DATE TIMESTAMP NOT NULL,PJ_REG_USER VARCHAR(50),PJ_INFO VARCHAR(1000), PJ_GROUP_ID VARCHAR(20) DEFAULT '', PJ_FAVORITE char(1));

CREATE TABLE ESB_SMS(PD_ID VARCHAR(22) NOT NULL PRIMARY KEY,SMS_SND_YN VARCHAR(1) NOT NULL);

CREATE TABLE INDIGO_FOLDER(FO_ID VARCHAR(22) NOT NULL PRIMARY KEY,FO_PID VARCHAR(22),FO_ORDER INTEGER NOT NULL,FO_PATH VARCHAR(200),FO_NAME VARCHAR(50) NOT NULL,FO_INFO VARCHAR(1000),FO_GUBUN VARCHAR(50),FO_REG_DATE TIMESTAMP,FO_REG_USER VARCHAR(50));
CREATE INDEX XIE1INDIGO_FOLDER ON INDIGO_FOLDER(FO_GUBUN,FO_PID);

CREATE TABLE INDIGO_CODE(CODE_DIV VARCHAR(10) NOT NULL,CODE_ID VARCHAR(100) NOT NULL,CODE_NAME VARCHAR(100),CODE_INFO VARCHAR(500),CODE_ORDER INTEGER DEFAULT 999 NOT NULL,USE_YN CHAR(1) DEFAULT 'Y' NOT NULL,PRIMARY KEY(CODE_DIV,CODE_ID));

CREATE TABLE INDIGO_USER(USER_ID VARCHAR(22) NOT NULL PRIMARY KEY,LOGIN_ID VARCHAR(20) NOT NULL,LOGIN_PW VARCHAR(100) NOT NULL,USER_NAME VARCHAR(50) NOT NULL,USER_EMAIL VARCHAR(200),USER_TEL VARCHAR(100),USER_SMS_YN VARCHAR(1),USER_INFO VARCHAR(1000),USER_GRP VARCHAR(50),AUTH_GRP VARCHAR(30),PW_CHANGE_YN VARCHAR(1),FINAL_LOGIN_DATE TIMESTAMP,CONSTRAINT SYS_CT_74 UNIQUE(LOGIN_ID));

INSERT INTO INDIGO_USER VALUES('00000000000000000XXXXX','ADMIN','ipnSjDxDyv7VjNusX06SAQ==','Administrator','','','N','','','SUPER','Y',null);
INSERT INTO INDIGO_FOLDER VALUES('00000000000000000AAAAA',NULL,1,'/','IService','','ISERVICE',NULL,NULL);

CREATE TABLE IMS_MSG_HUB_MASTER_LOG(TX_ID VARCHAR(60) NOT NULL PRIMARY KEY,IF_ID VARCHAR(64) DEFAULT NULL,MSG_CNT INTEGER DEFAULT 0,MSG_CREATE_DT CHAR(17) DEFAULT NULL,HUB_RCV_DT CHAR(17) DEFAULT NULL,MSG_TYPE CHAR(1) DEFAULT NULL);
CREATE TABLE IMS_MSG_HUB_CVT_RESULT_LOG(TX_ID VARCHAR(60) NOT NULL PRIMARY KEY,CVT_STATUS_CD CHAR(1) NOT NULL,MSG_CVT_DT CHAR(17) DEFAULT NULL,ERR_CNT INTEGER DEFAULT NULL,ERR_MSG BLOB);
CREATE TABLE IMS_MSG_HUB_DETAIL_LOG(TX_ID VARCHAR(60) NOT NULL,DEST_ID VARCHAR(64) NOT NULL,IF_ID VARCHAR(30),SND_CD CHAR(3),RCV_CD CHAR(3),SND_CNT INTEGER DEFAULT 0,MSG_CREATE_DT CHAR(17),HUB_CVT_DT CHAR(17),SND_AD_INST_NM VARCHAR(256),RCV_AD_INST_NM VARCHAR(256),RCV_QU_NM VARCHAR(256),SND_QU_NM VARCHAR(256),PRIMARY KEY(TX_ID,DEST_ID));
CREATE INDEX IMS_MSG_HUB_DETAIL_LOG_IDX ON IMS_MSG_HUB_DETAIL_LOG(MSG_CREATE_DT);
CREATE TABLE IMS_MSG_HUB_RESULT_LOG(TX_ID VARCHAR(60) NOT NULL,DEST_ID VARCHAR(64) NOT NULL,STATUS_CD CHAR(1) NOT NULL,MSG_RCV_DT CHAR(17) DEFAULT NULL,ERR_CNT INTEGER DEFAULT 0,ERR_MSG BLOB,PRIMARY KEY(TX_ID,DEST_ID));


CREATE TABLE INDIGO_PROPERTY(PROPERTY_ID VARCHAR(22) NOT NULL PRIMARY KEY, SERVICE_NAME VARCHAR(256) DEFAULT 'service' NOT NULL, NAME VARCHAR(256) NOT NULL, VALUE VARCHAR(4000) NOT NULL, INFO VARCHAR(4000) DEFAULT '', IS_USE CHAR(1) DEFAULT 'Y' NOT NULL, NAME_KOR VARCHAR(4000) DEFAULT '');

CREATE TABLE INDIGO_POLICY(SERVICE_ID  VARCHAR(256) PRIMARY KEY, USE_LOG CHAR(1) DEFAULT 'Y',USE_ABUSE CHAR(1) DEFAULT 'N', USE_DATE CHAR(1) DEFAULT 'N');

CREATE TABLE INDIGO_GROUP(GROUP_ID VARCHAR(100) PRIMARY KEY, GROUP_NAME VARCHAR(200),GROUP_INFO  VARCHAR(500) DEFAULT '');

CREATE TABLE INDIGO_GROUP_MAPPING(USER_ID VARCHAR(100), GROUP_ID VARCHAR(100), PRIMARY KEY(GROUP_ID,USER_ID));

CREATE TABLE INDIGO_SIMULATION_MSG(WEBSERVICE_NAME VARCHAR(30), MSG VARCHAR(4000), URL VARCHAR(100), GPKI_DN VARCHAR(20), TEST_NAME VARCHAR(30) DEFAULT '', SM_ID VARCHAR(22) DEFAULT '' PRIMARY KEY, TYPE CHAR(1));

CREATE TABLE INDIGO_SIMULATION_MSG_PROPERTY(PROP_ID VARCHAR(22) PRIMARY KEY, PROP_NAME VARCHAR(30), PROP_VALUE VARCHAR(30) , SM_ID VARCHAR(22));

CREATE TABLE ESB_ERROR_CHECK_LIST(ALIAS VARCHAR(50) NOT NULL PRIMARY KEY, IP VARCHAR(50), PORT VARCHAR(10), SYSTEM_NAME VARCHAR(100), DESCRIPTION VARCHAR(1000), URL VARCHAR(100), IN_DATE TIMESTAMP);

CREATE TABLE ESB_IMCHARGER(CH_ID BIGINT NOT NULL generated always as identity (start with 1, increment by 1) PRIMARY KEY , CHARGER_NAME VARCHAR(10) DEFAULT NULL, CHARGER_DEPTH VARCHAR(10) DEFAULT NULL, CHARGER_GROUP VARCHAR(30) DEFAULT NULL, CHARGER_TELNUM VARCHAR(15) DEFAULT NULL, CHARGER_CELLNUM VARCHAR(15) DEFAULT NULL, GUBUN_USER VARCHAR(1) DEFAULT NULL, GUBUN_LIVE VARCHAR(1) DEFAULT NULL, REG_DATE VARCHAR(17) DEFAULT NULL, IM_ID VARCHAR(2300) NOT NULL);

INSERT INTO INDIGO_GROUP VALUES ('indigo', 'indigo', 'DefaultGroup');

CREATE TABLE LIBBATCHUPDATE_ZIP(ZIPID VARCHAR(22) NOT NULL PRIMARY KEY, ZIPNAME VARCHAR(200) NOT NULL, DESCRIPTION VARCHAR(2000), REG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, ZIPSIZE VARCHAR(20), DESCRIPTION_ALIAS VARCHAR(40), ZIP_STATE VARCHAR(1) DEFAULT 'Y');
ALTER TABLE LIBBATCHUPDATE_ZIP ADD CHECKSUMSIZE VARCHAR(100);
ALTER TABLE LIBBATCHUPDATE_ZIP ADD DEPLOYTYPE VARCHAR(1);

CREATE TABLE LIBBATCHUPDATE_LIB (ID VARCHAR(50) NOT NULL PRIMARY KEY, LIBNAME VARCHAR(50) NOT NULL, TYPENAME VARCHAR(20) NOT NULL, PDTYPE VARCHAR(20), LIBSIZE VARCHAR(20), STATE VARCHAR(20) DEFAULT 'N' NOT NULL, ZIPID VARCHAR(22), DELFLAG VARCHAR(1) DEFAULT 'N');

CREATE TABLE LIBBATCHUPDATE_DEPLOY (DEPLOYID  VARCHAR(22) NOT NULL PRIMARY KEY, ZIPID VARCHAR(22), REG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE LIBBATCHUPDATE_STATUS (DEPLOYID  VARCHAR(22) NOT NULL , IM_NAME VARCHAR(50) NOT NULL, STATE VARCHAR(20) DEFAULT 'T' NOT NULL, REG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,	ERR_LOG  CLOB);
ALTER TABLE LIBBATCHUPDATE_STATUS ADD DEPLOYTYPE VARCHAR(1);
ALTER TABLE LIBBATCHUPDATE_STATUS ADD IM_IP VARCHAR(20);
ALTER TABLE LIBBATCHUPDATE_STATUS ADD START_DT VARCHAR(30);
ALTER TABLE LIBBATCHUPDATE_STATUS ADD END_DT VARCHAR(30);

ALTER TABLE LIBBATCHUPDATE_STATUS ADD PRIMARY KEY (DEPLOYID,IM_NAME);

CREATE TABLE WS_SQLINFO (SQLID VARCHAR(20) NOT NULL PRIMARY KEY, SQLNAME VARCHAR(20), QUERYID VARCHAR(20), ACTION VARCHAR(20), DATASOURCEID VARCHAR(20), SQLINFO VARCHAR(200), OPERATIONID VARCHAR(20),	POSSESINSTITUTEID VARCHAR(20), ADID VARCHAR(50), GROUPID VARCHAR(20) DEFAULT '', ADALIAS VARCHAR(100));

CREATE TABLE WS_INSTITUTEINFO (INSTITUTEID VARCHAR(20) NOT NULL PRIMARY KEY, INSTITUTENAME VARCHAR(20),	DEPTNAME VARCHAR(20), CHARGER VARCHAR(20), CHARGERNUMBER VARCHAR(30), INSTITUTEINFO VARCHAR(200));

CREATE TABLE WS_POSSESINSTITUTEINFO (POSSESINSTITUTEID VARCHAR(20) PRIMARY KEY NOT NULL, INSTITUTEIP VARCHAR(20), INSTITUTEPORT VARCHAR(20), POSSESREGDATE TIMESTAMP);

CREATE TABLE WS_INSTITUTEUSE (USEINSTITUTEID VARCHAR(20) NOT NULL PRIMARY KEY, USEREGDATE TIMESTAMP, USEIPLIST VARCHAR(100));
	
CREATE TABLE WS_INSTITUTEUSESQL (USEINSTITUTEID VARCHAR(20) NOT NULL, SQLID VARCHAR(20) NOT NULL, SQLUSEYN VARCHAR(1), SQLREGDATE TIMESTAMP, INTERFACEID VARCHAR(100) PRIMARY KEY);

CREATE TABLE WS_LOGGING (TRANSACTIONID VARCHAR(30), INTERFACEID VARCHAR(30), LOGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP, POSITION VARCHAR(1), STATE VARCHAR(1), MESSAGE VARCHAR(2000), MESSAGESIZE INTEGER, PRIMARY KEY(TRANSACTIONID,POSITION));

CREATE TABLE ESB_MONITOR_RESOURCE (MO_ID VARCHAR(22) NOT NULL PRIMARY KEY, MO_TYPE VARCHAR(3) NOT NULL, PD_ID VARCHAR(22) NOT NULL, CPU_USE VARCHAR(5), JVM_USE VARCHAR(5),	DISK_USE VARCHAR(5), MO_REG_DATE VARCHAR(25) NOT NULL);

-- ESB Resource Info 테이블
CREATE TABLE INDIGO_RESOURCE (MO_ID VARCHAR(22) NOT NULL PRIMARY KEY, HA_NAME VARCHAR(22) NOT NULL,	CPU_USE VARCHAR(5), MEM_USE VARCHAR(5), JVM_USE VARCHAR(5), DISK_USE VARCHAR(5), DISK_NAME VARCHAR(20),	BR_STORE VARCHAR(5), BR_MEM VARCHAR(5),	BR_TEMP VARCHAR(5), MO_REG_DATE VARCHAR(25) NOT NULL);

-- ESB Queue Info 테이블
CREATE TABLE INDIGO_QUEUE (MO_ID VARCHAR(22) NOT NULL PRIMARY KEY, HA_NAME VARCHAR(22) NOT NULL, Q_NAME VARCHAR(20) NOT NULL, Q_MEM VARCHAR(4), Q_SIZE INTEGER, Q_CONSUMER INTEGER,	MO_REG_DATE VARCHAR(25) NOT NULL);

-- ESB 컴포넌트 정보 테이블
CREATE TABLE INDIGO_COMPONENT (MO_ID VARCHAR(22) NOT NULL PRIMARY KEY, HA_NAME VARCHAR(22) NOT NULL, COMP_TYPE VARCHAR(9) NOT NULL,	COMP_NAME VARCHAR(50), COMP_STATUS VARCHAR(3), MO_REG_DATE VARCHAR(25));

/* 공통리소스 관리 */
CREATE TABLE INDIGO_CMM_RESOURCE (
  RESOURCE_KEY      VARCHAR(30)      NOT NULL PRIMARY KEY , 
  RESOURCE_TYPE     VARCHAR(255)      NOT NULL, 
  RESOURCE_ID       VARCHAR(255)      NOT NULL, 
  RESOURCE_ALIAS    VARCHAR(255)      NOT NULL,
  RESOURCE_USER    VARCHAR(255)      NOT NULL,
  RESOURCE_MEMO     VARCHAR(4000),
  RESOURCE_DATE VARCHAR(30)  
);

CREATE TABLE INDIGO_CMM_RESOURCE_PROPERTY (
  RESOURCE_PROPERTY_KEY      VARCHAR(30)     NOT NULL PRIMARY KEY, 
  RESOURCE_PROPERTY_NAME     VARCHAR(255)     NOT NULL, 
  RESOURCE_PROPERTY_VALUE    VARCHAR(4000)     NOT NULL, 
  RESOURCE_KEY               VARCHAR(30)
);

CREATE TABLE INDIGO_CMM_RESOURCE_MAPPING (
  RESOURCE_MAPPING_KEY    VARCHAR(30)     NOT NULL PRIMARY KEY, 
  RESOURCE_KEY            VARCHAR(30), 
  IN_ID                   VARCHAR(22), 
  MAPPING_DATE           VARCHAR(30)
);

/* 설정 히스토리 관리 */
CREATE TABLE INDIGO_CMM_RESOURCE_HISTORY (
  HISTORY_ID            VARCHAR(255)     NOT NULL, 
  HISTORY_FILE_CONTS    CLOB, 
  HISTORY_FILE_SIZE     VARCHAR(255), 
  HISTORY_DATE          VARCHAR(30)      NOT NULL, 
  USE_DATAYN            VARCHAR(1)       NOT NULL,
  HISTORY_VERSION		INTEGER			 NOT NULL,
  HISTORY_MEMO			VARCHAR(4000)
);

ALTER TABLE INDIGO_CMM_RESOURCE_HISTORY ADD PRIMARY KEY(HISTORY_ID, HISTORY_DATE);


ALTER TABLE ESB_INSTANCE_FILE		ADD HISTORY_ID VARCHAR(255);

ALTER TABLE ROUTE_INFO ADD   CONSTRAINT PK_ROUTE_INFO   PRIMARY KEY ( IF_ID, DEST_ID );
-- 변경된 IMS테이블 컬럼 추가
ALTER TABLE IMS_MSG_HUB_DETAIL_LOG ADD MSG_SIZE INTEGER;
ALTER TABLE IMS_MSG_HUB_DETAIL_LOG ADD SND_MSG BLOB;

ALTER TABLE IMS_MSG_HUB_MASTER_LOG ADD MSG_SIZE INTEGER;
ALTER TABLE IMS_MSG_HUB_MASTER_LOG ADD ESB_HOST VARCHAR(255);

ALTER TABLE IMS_MSG_HUB_RESULT_LOG ADD MSG_SIZE INTEGER;
ALTER TABLE IMS_MSG_HUB_RESULT_LOG ADD RETRY_CNT INTEGER;

-- 메시지 추적 테이블 추가

CREATE TABLE INDIGO_MESSAGETRACED
	(ID INTEGER NOT NULL, 
	PROPERTIES CLOB, 
	TIMESTAMP TIMESTAMP, 
	HEADERS CLOB, 
	EXCHANGEID VARCHAR(255), 
	BODY CLOB, 
	EXCHANGEPATTERN VARCHAR(255), 
	ROUTEID VARCHAR(255), 
	FROMENDPOINTURI VARCHAR(255), 
	PREVIOUSNODE VARCHAR(255), 
	TONODE VARCHAR(255), 
	SHORTEXCHANGEID VARCHAR(255), 
	BODYTYPE VARCHAR(255), 
	OUTBODY CLOB, 
	OUTBODYTYPE VARCHAR(255), 
	OUTHEADERS CLOB, 
	CAUSEDBYEXCEPTION CLOB, 
	"INOUT" VARCHAR(3), 
	STATUS CHAR(1), 
	NODEID VARCHAR(60), 
	GROUPEXCHANGEID VARCHAR(255), 
	TX_ID VARCHAR(60), 
	RETRY_COUNT INTEGER, 
	PREVIOUSNODEID VARCHAR(20), 
	PRIMARY KEY(ID)
	 );

	 CREATE INDEX INDIGO_MESSAGETRACED_I1 ON INDIGO_MESSAGETRACED (TX_ID);
	 CREATE INDEX INDIGO_MESSAGETRACED_I2 ON INDIGO_MESSAGETRACED (GROUPEXCHANGEID);
	 
	 CREATE SEQUENCE INDIGO_TRACE_SEQUENCE AS BIGINT MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 4421;

	 
-- 2016-10-10 JunHo Kim    master_log table index

CREATE INDEX IMS_MSG_HUB_MASTER_LOG_INDEX1 ON IMS_MSG_HUB_MASTER_LOG (MSG_CREATE_DT);
		
-- 2017-08-01 Dain Jin		created additional columns on indigo_user

ALTER TABLE INDIGO_USER ADD COLUMN PW_LAST_CHANGE_DTTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE INDIGO_USER ADD COLUMN PW_ERR_CNT INTEGER NOT NULL DEFAULT 0;
ALTER TABLE INDIGO_USER ADD COLUMN USER_STATUS CHAR(1) NOT NULL DEFAULT 'A';
ALTER TABLE INDIGO_USER ADD COLUMN ALLOWED_TML_IP VARCHAR(512);

-- 2017-08-09 Dain Jin		created user-interface mapping info.
-- 2018-06-05 Dain Jin		changed foreign key reference of USER_IF_MAPP_INFO.USER_ID from INDIGO_USER.USER_ID to INDIGO_GROUP.GROUP_ID 

CREATE TABLE USER_IF_MAPP_INFO (
	MAPP_ID VARCHAR(22) PRIMARY KEY,
	USER_ID VARCHAR(100) NOT NULL REFERENCES INDIGO_GROUP(GROUP_ID),
	IF_ID VARCHAR(64) NOT NULL
);

CREATE TABLE ESB_NOTICE 
(
  ID INTEGER PRIMARY KEY
, CONTS VARCHAR(2000) 
, REG_DATE CHAR(17) 
);

CREATE TABLE ESB_NOTIFY_MESSAGE 
(
  MESSAGE_ID VARCHAR(60) PRIMARY KEY 
, MESSAGE_STATUS CHAR(1) 
, COMPONENT_NAME VARCHAR(255) 
, CREATE_DATE DATE 
, DONE_YN CHAR(1) DEFAULT 'N' 
, DONE_DATE DATE 
, MESSAGE_CONTENT VARCHAR(4000) 
);

-- 모델러 프로젝트 테이블
CREATE TABLE INDIGO_MODELERPROJECT(
			 PROJECTID INTEGER PRIMARY KEY,
			 PROJECTNAME VARCHAR(30),
			 JSONTEXT BLOB,
			 BEANTEXT BLOB,
			 INFO VARCHAR(4000),
			 USERID VARCHAR(30),
			 TIMESTAMP TIMESTAMP,
			 FD_ID VARCHAR(20),
			 PROJECTALIAS VARCHAR(256)
);

-- 뉴템플릿 이력 MASTER 테이블
CREATE TABLE ESB_TEMP_IF_MASTER_LOG
(	IF_ID VARCHAR(40) NOT NULL, 
	TX_ID VARCHAR(64) NOT NULL, 
	TX_COUNT INTEGER, 
	TX_PROPERTY VARCHAR(4000), 
	TX_START_DATE VARCHAR(17), 
	TX_HUB_RCV_DATE VARCHAR(17), 
	ESB_HOST VARCHAR(255),
  CONSTRAINT M_LOG_PK PRIMARY KEY (IF_ID, TX_ID)
);

CREATE INDEX IDX_TX_START_DATE ON ESB_TEMP_IF_MASTER_LOG (
		TX_START_DATE
);

-- 뉴템플릿 이력 DETAIL 테이블
CREATE TABLE ESB_TEMP_IF_DEST_LOG 
(	TX_ID VARCHAR(64) NOT NULL, 
	DEST_ID VARCHAR(30) NOT NULL, 
	DEST_RCV_DATE VARCHAR(17), 
	DEST_RESULT CHAR(1), 
	RESULT_MESSAGE VARCHAR(4000), 
	REACTION_CNT INTEGER, 
	REACTION_DATE VARCHAR(17), 
	DEST_ERROR_COUNT INTEGER, 
	SEND_MESSAGE VARCHAR(4000), 
	 CONSTRAINT D_LOG_PK PRIMARY KEY (TX_ID, DEST_ID)
);

CREATE INDEX IDX_DEST_RCV_DATE ON ESB_TEMP_IF_DEST_LOG (
		DEST_RCV_DATE
);

-- 뉴템플릿 송신 인터페이스 테이블
CREATE TABLE ESB_TEMP_IF_MASTER 
(	IF_ID VARCHAR(40), 
	IF_NAME VARCHAR(100), 
	IF_TYPE VARCHAR(20), 
	SYSTEM_ID VARCHAR(20), 
	SYSTEM_NAME VARCHAR(64), 
	ROUTE_SEND_Q VARCHAR(40), 
	TARGET_LISTEN_Q VARCHAR(40), 
	ROUTE_RESULT_Q VARCHAR(40), 
	SOURCE_LISTEN_Q VARCHAR(40), 
	DESCRIPTION VARCHAR(4000), 
	REG_DATE TIMESTAMP, 
	MOD_DATE TIMESTAMP, 
	USE_YN CHAR(1), 
	 PRIMARY KEY (IF_ID)
);

-- 뉴템플릿 수신 인터페이스 테이블
CREATE TABLE ESB_TEMP_IF_DEST 
(	IF_ID VARCHAR(40) NOT NULL, 
	DEST_ID VARCHAR(10) NOT NULL, 
	IF_TYPE VARCHAR(20), 
	SYSTEM_ID VARCHAR(20), 
	SYSTEM_NAME VARCHAR(64), 
	DESCRIPTION VARCHAR(4000), 
	REG_DATE TIMESTAMP, 
	MOD_DATE TIMESTAMP, 
	 CONSTRAINT UNIQUE_PK PRIMARY KEY (IF_ID, DEST_ID)
);
