DROP TABLE ROUTE_INFO CASCADE CONSTRAINTS;
DROP TABLE INDIGO_SECURITY CASCADE CONSTRAINTS;
DROP TABLE ESB_IMANAGER CASCADE CONSTRAINTS;
DROP TABLE ESB_ISERVICE_VER CASCADE CONSTRAINTS;
DROP TABLE ESB_HOST CASCADE CONSTRAINTS;
DROP TABLE ESB_SMS CASCADE CONSTRAINTS;
DROP TABLE ESB_INSTANCE_FILE CASCADE CONSTRAINTS;
DROP TABLE ESB_DEPLOY_MAPPING CASCADE CONSTRAINTS;
DROP TABLE ESB_INSTANCE CASCADE CONSTRAINTS;
DROP TABLE ESB_PROJECT CASCADE CONSTRAINTS;
DROP TABLE ESB_ISERVICE CASCADE CONSTRAINTS;
DROP TABLE ESB_MONITOR CASCADE CONSTRAINTS;
DROP TABLE ESB_PRODUCT CASCADE CONSTRAINTS;
DROP TABLE INDIGO_FOLDER CASCADE CONSTRAINTS;
DROP TABLE INDIGO_CODE CASCADE CONSTRAINTS;
DROP TABLE INDIGO_USER CASCADE CONSTRAINTS;
DROP TABLE IMS_MSG_HUB_MASTER_LOG CASCADE CONSTRAINTS;
DROP TABLE IMS_MSG_HUB_DETAIL_LOG CASCADE CONSTRAINTS;
DROP TABLE IMS_MSG_HUB_RESULT_LOG CASCADE CONSTRAINTS;
DROP TABLE IMS_MSG_HUB_CVT_RESULT_LOG CASCADE CONSTRAINTS;
DROP TABLE INDIGO_PROPERTY CASCADE CONSTRAINTS;
DROP TABLE INDIGO_POLICY CASCADE CONSTRAINTS;
DROP TABLE INDIGO_GROUP CASCADE CONSTRAINTS;
DROP TABLE INDIGO_GROUP_MAPPING CASCADE CONSTRAINTS;
DROP TABLE INDIGO_SIMULATION_MSG CASCADE CONSTRAINTS;
DROP TABLE ESB_ERROR_CHECK_LIST CASCADE CONSTRAINTS;
DROP TABLE INDIGO_SIMULATION_MSG_PROPERTY CASCADE CONSTRAINTS;
DROP TABLE ESB_IMCHARGER CASCADE CONSTRAINTS;
DROP TABLE LIBBATCHUPDATE_ZIP CASCADE CONSTRAINTS;
DROP TABLE LIBBATCHUPDATE_LIB CASCADE CONSTRAINTS;
DROP TABLE LIBBATCHUPDATE_DEPLOY CASCADE CONSTRAINTS;
DROP TABLE LIBBATCHUPDATE_STATUS CASCADE CONSTRAINTS;
DROP TABLE WS_SQLINFO CASCADE CONSTRAINTS;
DROP TABLE WS_INSTITUTEINFO CASCADE CONSTRAINTS;
DROP TABLE WS_POSSESINSTITUTEINFO CASCADE CONSTRAINTS;
DROP TABLE WS_INSTITUTEUSE CASCADE CONSTRAINTS;
DROP TABLE WS_INSTITUTEUSESQL CASCADE CONSTRAINTS;
DROP TABLE WS_LOGGING CASCADE CONSTRAINTS;
DROP TABLE ESB_MONITOR_RESOURCE CASCADE CONSTRAINTS;
DROP TABLE INDIGO_RESOURCE CASCADE CONSTRAINTS;
DROP TABLE INDIGO_QUEUE CASCADE CONSTRAINTS;
DROP TABLE INDIGO_COMPONENT CASCADE CONSTRAINTS;
DROP SEQUENCE CHARGER;

/* 공통리소스 관리 */
DROP TABLE INDIGO_CMM_RESOURCE_MAPPING CASCADE CONSTRAINTS;
DROP TABLE INDIGO_CMM_RESOURCE_PROPERTY CASCADE CONSTRAINTS;
DROP TABLE INDIGO_CMM_RESOURCE CASCADE CONSTRAINTS;
DROP TABLE INDIGO_CMM_RESOURCE_HISTORY CASCADE CONSTRAINTS;

/* 메시지 기능 관련 DROP 2016.05.19 작성자 : 장준환 */

DROP SEQUENCE COLUMNNUM_SEQUENCE;
DROP TABLE DB_COLUMN;
DROP TABLE DB_TABLE;
DROP TABLE DB_MESSAGE;
DROP TABLE MESSAGE_INFO;

/* 인터페이스, 기관 정보, 매핑 관련 DROP 2016.05.23 작성자: 진다인 */
DROP TABLE MAPPING CASCADE CONSTRAINTS;
DROP TABLE INTERFACE_INFO CASCADE CONSTRAINTS;
DROP TABLE INSTITUTE_INFO CASCADE CONSTRAINTS;

/* 메시지 이력 상세 */
DROP TABLE INDIGO_MESSAGETRACED;

CREATE TABLE ROUTE_INFO (
  IF_ID                VARCHAR2(64)       NOT NULL, 
  DEST_ID              VARCHAR2(64)       NOT NULL, 
  SND_CD               VARCHAR2(30)       NOT NULL, 
  RCV_CD               VARCHAR2(30)       NOT NULL, 
  DATA_ARR_QUEUE       VARCHAR2(50)       NOT NULL, 
  DATA_DEST_QUEUE      VARCHAR2(50)       NOT NULL, 
  RESULT_ARR_QUEUE     VARCHAR2(50)       NOT NULL, 
  RESULT_DEST_QUEUE    VARCHAR2(50)       NOT NULL, 
  REMOTE_YN            VARCHAR2(1)        NOT NULL, 
  CHANGE_DATE          VARCHAR2(17)       NOT NULL, 
  DESCRIPTION          VARCHAR2(4000)         NULL, 
  USING_IP             VARCHAR2(4000)         NULL, 
  USE_YN               CHAR(1)           DEFAULT 'N'                NULL
);

COMMENT ON COLUMN ROUTE_INFO.IF_ID IS '인터페이스 아이디';

COMMENT ON COLUMN ROUTE_INFO.DEST_ID IS '목적지 아이디';

COMMENT ON COLUMN ROUTE_INFO.SND_CD IS '송신 시스템 약자';

COMMENT ON COLUMN ROUTE_INFO.RCV_CD IS '수신 시스템 약자';

COMMENT ON COLUMN ROUTE_INFO.DATA_ARR_QUEUE IS '데이터 적재 큐';

COMMENT ON COLUMN ROUTE_INFO.DATA_DEST_QUEUE IS '데이터 목적 큐';

COMMENT ON COLUMN ROUTE_INFO.RESULT_ARR_QUEUE IS '결과 적재 큐';

COMMENT ON COLUMN ROUTE_INFO.RESULT_DEST_QUEUE IS '결과 목적 큐';

COMMENT ON COLUMN ROUTE_INFO.REMOTE_YN IS '원격호출(api) 사용 여부';

COMMENT ON COLUMN ROUTE_INFO.CHANGE_DATE IS '등록/변경 날짜';

COMMENT ON COLUMN ROUTE_INFO.DESCRIPTION IS '설명';

COMMENT ON COLUMN ROUTE_INFO.USING_IP IS '송신측 서버 아이피';

COMMENT ON COLUMN ROUTE_INFO.USE_YN IS '라우팅 사용 여부';

ALTER TABLE ROUTE_INFO ADD
(
    CONSTRAINT ROUTE_INFO_PK
    PRIMARY KEY ( IF_ID, DEST_ID )
);

/* ROUTE_INFO에 IF_NAME(인터페이스 이름)컬럼 추가 */
ALTER TABLE ROUTE_INFO ADD (IF_NAME VARCHAR2(100));

CREATE TABLE INDIGO_SECURITY 
(
  SECURITY_ID VARCHAR2(255) 
, SECURITY_KEY CHAR(32) PRIMARY KEY
, USE_KEY CHAR(1) DEFAULT 'Y'
, CREATE_DATE VARCHAR2(30) DEFAULT TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISSFF3')  
);

CREATE TABLE ESB_DEPLOY_MAPPING (
       IN_ID                VARCHAR2(22) NOT NULL,
       IS_ID                VARCHAR2(22) NOT NULL,
       CONSTRAINT ESB_DEPLOY_MAPPING_PK PRIMARY KEY(IN_ID, IS_ID)
);

CREATE TABLE ESB_HOST (
       HOST_NAME            VARCHAR2(50) NOT NULL,
       HOST_IP              VARCHAR2(40) NOT NULL,
       HOST_ORDER           INTEGER NOT NULL,
       CONSTRAINT ESB_HOST_PK PRIMARY KEY(HOST_NAME)
);

CREATE TABLE  ESB_IMANAGER (
       IM_ID                VARCHAR2(22) NOT NULL,
       IM_IP                VARCHAR2(40) NOT NULL,
       IM_PORT              VARCHAR2(5) NOT NULL,
       IM_OS                VARCHAR2(100) NULL,
       IM_INFO              VARCHAR2(1000) NULL,
       IM_VER               VARCHAR2(20) NULL,
       SYSTEM_ID            VARCHAR2(20) DEFAULT '',
       IM_COMMUNICATION 	VARCHAR2(10) DEFAULT 'jms',
       CONSTRAINT ESB_IMANAGER_PK PRIMARY KEY(IM_ID)
);

CREATE TABLE ESB_INSTANCE (
       IN_ID                   VARCHAR2(22) NOT NULL,
       PJ_ID                   VARCHAR2(22) NULL,
       IN_INFO                 VARCHAR2(1000) NULL,
       IN_DEPLOY_YN            VARCHAR2(1) NULL,
       IN_DEPLOY_DATE          DATE NULL,
       IN_START_XMS            VARCHAR2(5) NULL,
       IN_START_XMX            VARCHAR2(5) NULL,
       IN_COMPILER_OPT         VARCHAR2(500) NULL,
       IN_AUTOSTART_YN         VARCHAR2(1) NULL,
       IN_AUTOSTART_CNT        INTEGER NULL,
       IN_PORT                 VARCHAR2(10),
       IN_EXCLUSIVE_CLASSPATH  VARCHAR2(1024) DEFAULT '',
       CONSTRAINT ESB_INSTANCE_PK PRIMARY KEY(IN_ID)

);

CREATE INDEX IDX_ESB_INSTANCE ON ESB_INSTANCE (
       PJ_ID                 ASC
);

CREATE TABLE ESB_INSTANCE_FILE (
       IN_ID                VARCHAR2(22) NOT NULL,
       IN_FILE_ID           INTEGER NOT NULL,
       IN_FILE_NAME         VARCHAR2(100) NOT NULL,
       IN_FILE_CONTS        BLOB NULL,
       CONSTRAINT ESB_INSTANCE_FILE_PK PRIMARY KEY(IN_ID, IN_FILE_ID)
);

CREATE TABLE ESB_ISERVICE (
       IS_ID                VARCHAR2(22) NOT NULL,
       IS_ORDER             INTEGER NOT NULL,
       IS_FILE_NAME         VARCHAR2(200) NOT NULL,
       IS_INFO              VARCHAR2(1000) NULL,
       IS_USE_VER           INTEGER NOT NULL,
       FO_ID                VARCHAR2(22) NOT NULL,
       CONSTRAINT ESB_ISERVICE_PK PRIMARY KEY(IS_ID)
);

CREATE TABLE ESB_ISERVICE_VER (
       IS_ID                VARCHAR2(22) NOT NULL,
       IS_VER               INTEGER NOT NULL,
       IS_REG_USER          VARCHAR2(50) NULL,
       IS_REG_DATE          DATE NULL,
       IS_FILE_SIZE         INTEGER NULL,
       IS_FILE              BLOB NOT NULL,
       IS_INFO 				VARCHAR2(1000),
       CONSTRAINT ESB_ISERVICE_VER_PK PRIMARY KEY(IS_ID, IS_VER)
);

CREATE TABLE ESB_MONITOR (
       MO_ID                VARCHAR2(22) NOT NULL,
       IM_STATUS            VARCHAR2(2) NULL,
       NW_STATUS            VARCHAR2(2) NULL,
       DS_STATUS            VARCHAR2(2) NULL,
       CPU_USE              VARCHAR2(10) NULL,
       MEMORY_USE           VARCHAR2(10) NULL,
       CPU_TIME             VARCHAR2(10) NULL,
       ELAPSED_TIME         VARCHAR2(20) NULL,
       MO_REG_DATE          DATE NOT NULL,
       MO_STATUS            VARCHAR2(2) NULL,
       PD_ID                VARCHAR2(22) NOT NULL,
       CONSTRAINT ESB_MONITOR_PK PRIMARY KEY(MO_ID)
);

CREATE INDEX IDX_ESB_MONITOR ON ESB_MONITOR (
       PD_ID                          ASC
);

CREATE TABLE ESB_PRODUCT (
       PD_ID                VARCHAR2(22) NOT NULL,
       PD_TYPE              VARCHAR2(2) NULL,
       PD_ORDER             INTEGER NOT NULL,
       PD_NAME              VARCHAR2(100) NOT NULL,
       PD_ALIAS             VARCHAR2(100) NULL,
       PD_REG_DATE          DATE NULL,
       PD_REG_USER          VARCHAR2(50) NULL,
       IN_IM_ID             VARCHAR2(22) NULL,
       FINAL_NW_STATUS      VARCHAR2(2) NULL,
       FINAL_MO_STATUS      VARCHAR2(2) NULL,
       FINAL_MO_REG_DATE    DATE NULL,
       MO_ERROR_CNT         INTEGER NOT NULL,
       FINAL_DS_STATUS      VARCHAR2(2) DEFAULT '',
       PD_FAVORITE          CHAR(1),                        
       PD_FIREWALL          CHAR(1),                       
       PD_GROUP_ID          VARCHAR2(20) DEFAULT '',
       CONSTRAINT ESB_PRODUCT_PK PRIMARY KEY(PD_ID),
       CONSTRAINT ESB_PRODUCT_UK UNIQUE(PD_NAME)
);

COMMENT ON COLUMN ESB_PRODUCT.PD_FIREWALL      IS '에이전트 트리메뉴 추가여부';
COMMENT ON COLUMN ESB_PRODUCT.PD_GROUP_ID      IS '에이전트 방화벽 설정값';

CREATE INDEX IDX_ESB_PRODUCT ON ESB_PRODUCT (
       IN_IM_ID                       ASC
);

CREATE TABLE ESB_PROJECT (
       PJ_ID                VARCHAR2(22) NOT NULL,
       PJ_ORDER             INTEGER NOT NULL,
       PJ_NAME              VARCHAR2(50) NOT NULL,
       PJ_REG_DATE          DATE NOT NULL,
       PJ_REG_USER          VARCHAR2(50) NULL,
       PJ_INFO              VARCHAR2(1000) NULL,
       PJ_GROUP_ID          VARCHAR2(20) DEFAULT '',
       PJ_FAVORITE          CHAR(1),
       CONSTRAINT ESB_PROJECT_PK PRIMARY KEY(PJ_ID)
);

COMMENT ON COLUMN ESB_PROJECT.PJ_FAVORITE IS '프로젝트 트리메뉴 추가여부';

CREATE TABLE ESB_SMS (
       PD_ID                VARCHAR2(22) NOT NULL,
       SMS_SND_YN           VARCHAR2(1) NOT NULL,
       CONSTRAINT ESB_SMS_PK PRIMARY KEY(PD_ID)
);

CREATE TABLE INDIGO_FOLDER (
       FO_ID                VARCHAR2(22) NOT NULL,
       FO_PID               VARCHAR2(22) NULL,
       FO_ORDER             INTEGER NOT NULL,
       FO_PATH              VARCHAR2(200) NULL,
       FO_NAME              VARCHAR2(50) NOT NULL,
       FO_INFO              VARCHAR2(1000) NULL,
       FO_GUBUN             VARCHAR2(50) NULL,
       FO_REG_DATE          DATE NULL,
       FO_REG_USER          VARCHAR2(50) NULL,
       CONSTRAINT INDIGO_FOLDER_PK PRIMARY KEY(FO_ID)
);

CREATE INDEX IDX_INDIGO_FOLDER ON INDIGO_FOLDER (
       FO_GUBUN                       ASC,
       FO_PID                         ASC       
);

INSERT INTO INDIGO_FOLDER (FO_ID, FO_ORDER, FO_PATH, FO_NAME, FO_PID, FO_INFO, FO_GUBUN, FO_REG_DATE, FO_REG_USER)
VALUES('00000000000000000AAAAA', 1, '/', 'IService', null, '', 'ISERVICE', sysdate, 'admin');

CREATE TABLE INDIGO_CODE (
		CODE_DIV		VARCHAR2(10) NOT NULL,
		CODE_ID			VARCHAR2(100) NOT NULL,
		CODE_NAME		VARCHAR2(100) NULL,
		CODE_INFO		VARCHAR2(500) NULL,
		CODE_ORDER 		INTEGER DEFAULT 999 NOT NULL,
		USE_YN			CHAR(1) DEFAULT 'Y' NOT NULL,
		CONSTRAINT INDIGO_CODE_PK PRIMARY KEY(CODE_DIV, CODE_ID)
);

CREATE TABLE INDIGO_USER (
		USER_ID              VARCHAR2(22) NOT NULL,
		LOGIN_ID             VARCHAR2(20) NOT NULL,
		LOGIN_PW             VARCHAR2(100) NOT NULL,
		USER_NAME            VARCHAR2(50) NOT NULL,
		USER_EMAIL           VARCHAR2(200) NULL,
		USER_TEL             VARCHAR2(100) NULL,
		USER_SMS_YN          VARCHAR2(1) NULL,
		USER_INFO            VARCHAR2(1000) NULL,
		USER_GRP             VARCHAR2(50) NULL,
		AUTH_GRP             VARCHAR2(30) NULL,
		PW_CHANGE_YN         VARCHAR2(1) NULL,
		FINAL_LOGIN_DATE     DATE NULL,
		CONSTRAINT INDIGO_USER_PK PRIMARY KEY(USER_ID),
		CONSTRAINT INDIGO_USER_UK UNIQUE(LOGIN_ID)
);

INSERT INTO INDIGO_USER (USER_ID, LOGIN_ID, LOGIN_PW, USER_NAME, USER_EMAIL, USER_TEL, USER_SMS_YN, USER_INFO, USER_GRP, AUTH_GRP, PW_CHANGE_YN, FINAL_LOGIN_DATE)
VALUES('00000000000000000XXXXX', 'ADMIN', 'ipnSjDxDyv7VjNusX06SAQ==', 'Administrator', '', '', 'N', '', '', 'SUPER', 'Y', null);

CREATE TABLE IMS_MSG_HUB_MASTER_LOG (
		TX_ID          CHAR(42),                  
		IF_ID          VARCHAR2(64),              
		MSG_CNT        NUMBER DEFAULT 0,          
		MSG_CREATE_DT  CHAR(17),                  
		HUB_RCV_DT     CHAR(17),                  
		MSG_TYPE       CHAR(1),
		CONSTRAINT IMS_MSG_HUB_MASTER_LOG_PK PRIMARY KEY(TX_ID)
 );                  
  
COMMENT ON COLUMN IMS_MSG_HUB_MASTER_LOG.TX_ID IS '트랜젝션 아이디';
COMMENT ON COLUMN IMS_MSG_HUB_MASTER_LOG.IF_ID IS '인터페이스 아이디';
COMMENT ON COLUMN IMS_MSG_HUB_MASTER_LOG.MSG_CNT IS '메세지 발생 건수';
COMMENT ON COLUMN IMS_MSG_HUB_MASTER_LOG.MSG_CREATE_DT IS '메세지 생성 시간';
COMMENT ON COLUMN IMS_MSG_HUB_MASTER_LOG.HUB_RCV_DT IS 'HUB 메세지 수신 시간';
COMMENT ON COLUMN IMS_MSG_HUB_MASTER_LOG.MSG_TYPE IS '메시지 종류 ( T: 증폭, N: 일반)A';

CREATE TABLE IMS_MSG_HUB_CVT_RESULT_LOG (
		TX_ID          CHAR(42),                 
		CVT_STATUS_CD  CHAR(1) NOT NULL,         
		MSG_CVT_DT     CHAR(17),                 
		ERR_CNT        NUMBER DEFAULT 0,               
		ERR_MSG        BLOB,
		CONSTRAINT IMS_MSG_HUB_CVT_RESULT_LOG_PK PRIMARY KEY(TX_ID)
);                    
  
COMMENT ON COLUMN IMS_MSG_HUB_CVT_RESULT_LOG.TX_ID IS '트렌젝션 아이디';
COMMENT ON COLUMN IMS_MSG_HUB_CVT_RESULT_LOG.CVT_STATUS_CD IS '변환상태 코드 (F: 변환 실패)';
COMMENT ON COLUMN IMS_MSG_HUB_CVT_RESULT_LOG.MSG_CVT_DT IS '메세지 변환 시간';
COMMENT ON COLUMN IMS_MSG_HUB_CVT_RESULT_LOG.ERR_CNT IS '전체 데이타중 변환 실패 한 건수';
COMMENT ON COLUMN IMS_MSG_HUB_CVT_RESULT_LOG.ERR_MSG IS '변환 실패 매세지 원본';
 
CREATE TABLE IMS_MSG_HUB_DETAIL_LOG (
		TX_ID           CHAR(42),                 
		DEST_ID         VARCHAR2(64),             
		IF_ID           VARCHAR2(18),             
		SND_CD          CHAR(3),                  
		RCV_CD          CHAR(3),                  
		SND_CNT         NUMBER DEFAULT 0,         
		MSG_CREATE_DT   CHAR(17),                 
		HUB_CVT_DT      CHAR(17),                 
		SND_AD_INST_NM  VARCHAR2(256),            
		RCV_AD_INST_NM  VARCHAR2(256),            
		RCV_QU_NM       VARCHAR2(256),            
		SND_QU_NM       VARCHAR2(256),
		CONSTRAINT IMS_MSG_HUB_DETAIL_LOG_PK PRIMARY KEY(TX_ID, DEST_ID)
);           
  
COMMENT ON COLUMN IMS_MSG_HUB_DETAIL_LOG.TX_ID          IS '트렌젝션 아이디';
COMMENT ON COLUMN IMS_MSG_HUB_DETAIL_LOG.DEST_ID        IS '메세지 수신지 주소';
COMMENT ON COLUMN IMS_MSG_HUB_DETAIL_LOG.IF_ID          IS '인터페이스 아이디';
COMMENT ON COLUMN IMS_MSG_HUB_DETAIL_LOG.SND_CD         IS '송신지 구분 코드';
COMMENT ON COLUMN IMS_MSG_HUB_DETAIL_LOG.RCV_CD         IS '수신지 구분 코드';
COMMENT ON COLUMN IMS_MSG_HUB_DETAIL_LOG.SND_CNT        IS '메제시 묵음 단위';
COMMENT ON COLUMN IMS_MSG_HUB_DETAIL_LOG.MSG_CREATE_DT  IS '메세지 생성신간';
COMMENT ON COLUMN IMS_MSG_HUB_DETAIL_LOG.HUB_CVT_DT     IS '메세지 변환시간: ESB 메세지 변환시간';
COMMENT ON COLUMN IMS_MSG_HUB_DETAIL_LOG.SND_AD_INST_NM IS '임시 : 송신 어댑터 인스턴스 명 (현재사용안함';
COMMENT ON COLUMN IMS_MSG_HUB_DETAIL_LOG.RCV_AD_INST_NM IS '임시 : 수신 어댑터 인스턴스 명(현재사용안함)';
COMMENT ON COLUMN IMS_MSG_HUB_DETAIL_LOG.RCV_QU_NM      IS '임시 : 수신 큐 이름(현재사용안함)';
COMMENT ON COLUMN IMS_MSG_HUB_DETAIL_LOG.SND_QU_NM      IS '임시 : 송신 큐 이름(현재사용안함)';

CREATE INDEX IDX_IMS_MSG_HUB_DETAIL_LOG ON IMS_MSG_HUB_DETAIL_LOG (
		MSG_CREATE_DT
);

CREATE INDEX IDX_IMS_MSG_HUB_RESULT_LOG ON IMS_MSG_HUB_RESULT_LOG (
		MSG_RCV_DT
);

CREATE TABLE IMS_MSG_HUB_RESULT_LOG (
		TX_ID       CHAR(42),                   
		DEST_ID     VARCHAR2(64),               
		STATUS_CD   CHAR(1) NOT NULL,           
		MSG_RCV_DT  CHAR(17),                   
		ERR_CNT     NUMBER DEFAULT 0,           
		ERR_MSG     BLOB,
		CONSTRAINT IMS_MSG_HUB_RESULT_LOG_PK PRIMARY KEY(TX_ID, DEST_ID)
);                      
  
COMMENT ON COLUMN IMS_MSG_HUB_RESULT_LOG.TX_ID      IS '트랙젝션 이아디';
COMMENT ON COLUMN IMS_MSG_HUB_RESULT_LOG.DEST_ID    IS '수신지 주소';
COMMENT ON COLUMN IMS_MSG_HUB_RESULT_LOG.STATUS_CD  IS '처리결과 상태코드 (F: 실패, R:재처리)';
COMMENT ON COLUMN IMS_MSG_HUB_RESULT_LOG.MSG_RCV_DT IS '메세지 수신시간';
COMMENT ON COLUMN IMS_MSG_HUB_RESULT_LOG.ERR_CNT    IS '전체 데이타중 에러 발생 건수';
COMMENT ON COLUMN IMS_MSG_HUB_RESULT_LOG.ERR_MSG    IS '에러 메세지 원본';


-- IMS 테이블(TX_ID CHAR->VARCHAR2   &&   어댑터템플릿 사용을 위해 TX_ID 길이 60으로 수정)
ALTER TABLE IMS_MSG_HUB_CVT_RESULT_LOG
MODIFY (
  TX_ID VARCHAR2(60)
);

ALTER TABLE IMS_MSG_HUB_DETAIL_LOG
MODIFY (
  TX_ID VARCHAR2(60)
);

ALTER TABLE IMS_MSG_HUB_MASTER_LOG
MODIFY (
  TX_ID VARCHAR2(60)
);

ALTER TABLE IMS_MSG_HUB_RESULT_LOG
MODIFY (
  TX_ID VARCHAR2(60)
);


CREATE TABLE INDIGO_PROPERTY (
		PROPERTY_ID     VARCHAR2(22) NOT NULL,
		SERVICE_NAME    VARCHAR2(256) DEFAULT 'service' NOT NULL,
		NAME             VARCHAR2(256) NOT NULL,
		VALUE           VARCHAR2(4000) NOT NULL,
		INFO            VARCHAR2(4000) DEFAULT '',
		IS_USE          CHAR(1) DEFAULT 'Y' NOT NULL,
		NAME_KOR        VARCHAR2(4000) DEFAULT '',
		CONSTRAINT INDIGO_PROPERTY_PK PRIMARY KEY(PROPERTY_ID)
);

CREATE TABLE INDIGO_POLICY (
		SERVICE_ID  VARCHAR2(256),
		USE_LOG     CHAR(1) DEFAULT 'Y',
		USE_ABUSE   CHAR(1) DEFAULT 'N',
		USE_DATE    CHAR(1) DEFAULT 'N',
		CONSTRAINT INDIGO_POLICY_PK PRIMARY KEY(SERVICE_ID)
);

CREATE TABLE  INDIGO_GROUP (
		GROUP_ID    VARCHAR2(100),
		GROUP_NAME  VARCHAR2(200),
		GROUP_INFO  VARCHAR2(500) DEFAULT '',
		CONSTRAINT INDIGO_GROUP_PK PRIMARY KEY(GROUP_ID)
);

INSERT INTO INDIGO_GROUP (GROUP_ID, GROUP_NAME, GROUP_INFO) 
VALUES ('indigo', 'indigo', 'DefaultGroup');

CREATE TABLE INDIGO_GROUP_MAPPING (
		USER_ID     VARCHAR2(100),
		GROUP_ID    VARCHAR2(100),
		CONSTRAINT INDIGO_GROUP_MAPPING_PK PRIMARY KEY(GROUP_ID,USER_ID)
);

CREATE TABLE INDIGO_SIMULATION_MSG (
		WEBSERVICE_NAME VARCHAR2(30),
		MSG             VARCHAR2(4000),
		URL             VARCHAR2(100),
		GPKI_DN         VARCHAR2(20),
		TEST_NAME       VARCHAR2(30) DEFAULT '',
		SM_ID           VARCHAR2(22) DEFAULT '',
		TYPE			CHAR(1),
		CONSTRAINT INDIGO_SIMULATION_MSG_PK PRIMARY KEY(SM_ID)
);
--  20130328 jms 테스트 관련 TYPE컬럼 추가 : 테스트 메시지 타입(M: mq, W: ws)

CREATE TABLE INDIGO_SIMULATION_MSG_PROPERTY (
		PROP_ID VARCHAR2(22 BYTE) NOT NULL,
		PROP_NAME VARCHAR2(30 BYTE) ,
		PROP_VALUE VARCHAR2(30 BYTE) ,
		SM_ID VARCHAR2(22 BYTE) ,
		CONSTRAINT SIMULATION_MSG_PROPERTY_PK PRIMARY KEY(PROP_ID)
);

-- JMS 테스트 속성이름컬럼 길이 증가
ALTER TABLE INDIGO_SIMULATION_MSG_PROPERTY MODIFY (
  PROP_NAME VARCHAR2(40)
);


CREATE TABLE ESB_ERROR_CHECK_LIST (
		ALIAS       VARCHAR2(50) NOT NULL,
		IP          VARCHAR2(50),
		PORT        VARCHAR2(10),
		SYSTEM_NAME VARCHAR2(100),
		DESCRIPTION VARCHAR2(1000),
		URL         VARCHAR2(100),
		IN_DATE     DATE,
		CONSTRAINT ESB_ERROR_CHECK_LIST_PK PRIMARY KEY(ALIAS)
);

CREATE TABLE ESB_IMCHARGER (
		CH_ID              NUMBER             NOT NULL, 
		CHARGER_NAME       VARCHAR2(10)           NULL, 
		CHARGER_DEPTH      VARCHAR2(10)           NULL, 
		CHARGER_GROUP      VARCHAR2(30)           NULL, 
		CHARGER_TELNUM     VARCHAR2(15)           NULL, 
		CHARGER_CELLNUM    VARCHAR2(15)           NULL, 
		GUBUN_USER         VARCHAR2(1)            NULL, 
		GUBUN_LIVE         VARCHAR2(1)            NULL, 
		REG_DATE           VARCHAR2(17)           NULL, 
		IM_ID              VARCHAR2(2300)         NULL,
		CONSTRAINT ESB_IMCHARGER_PK PRIMARY KEY(CH_ID) USING INDEX
);

COMMENT ON COLUMN ESB_IMCHARGER.CH_ID IS 'seq';
COMMENT ON COLUMN ESB_IMCHARGER.CHARGER_NAME IS '담당자 이름';
COMMENT ON COLUMN ESB_IMCHARGER.CHARGER_DEPTH IS '담당자 직책';
COMMENT ON COLUMN ESB_IMCHARGER.CHARGER_GROUP IS '담당자 소속';
COMMENT ON COLUMN ESB_IMCHARGER.CHARGER_TELNUM IS '담당자 유선전화';
COMMENT ON COLUMN ESB_IMCHARGER.CHARGER_CELLNUM IS '담당자 휴대폰';
COMMENT ON COLUMN ESB_IMCHARGER.GUBUN_USER IS '고객인지 Y 엔지니어인지 N';
COMMENT ON COLUMN ESB_IMCHARGER.GUBUN_LIVE IS '관리중인지 아닌지 Y.N';
COMMENT ON COLUMN ESB_IMCHARGER.REG_DATE IS '등록일';
COMMENT ON COLUMN ESB_IMCHARGER.IM_ID IS 'IM_ID';

CREATE SEQUENCE CHARGER
		START WITH 41
		INCREMENT BY 1
		MAXVALUE 999999999999999999999999999
		MINVALUE 1
		NOCYCLE
		CACHE 20
		NOORDER;
    
-- LibBatchUpdate table 추가
CREATE TABLE LIBBATCHUPDATE_ZIP(
		ZIPID       		VARCHAR2(22 BYTE)                NOT NULL,
		ZIPNAME      		VARCHAR2(200 BYTE)               NOT NULL,
		DESCRIPTION  		VARCHAR2(2000 BYTE),
		REG_DT 				VARCHAR2(30 BYTE) DEFAULT TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISSFF3'), 
		ZIPSIZE 			VARCHAR2(20 BYTE), 
		DESCRIPTION_ALIAS 	VARCHAR2(40 BYTE), 
		ZIP_STATE 			VARCHAR2(1 BYTE) DEFAULT 'Y',
		CONSTRAINT LIBBATCHUPDATE_ZIP_PK PRIMARY KEY(ZIPID)
);

COMMENT ON TABLE LIBBATCHUPDATE_ZIP IS 'LiveUpdate Master';
COMMENT ON COLUMN LIBBATCHUPDATE_ZIP.ZIPNAME IS '압축파일명';
COMMENT ON COLUMN LIBBATCHUPDATE_ZIP.DESCRIPTION IS '설명 ( 버전 )';
COMMENT ON COLUMN LIBBATCHUPDATE_ZIP.ZIPID IS '압축파일ID';

CREATE TABLE LIBBATCHUPDATE_LIB (
		ID        VARCHAR2(50 BYTE)                   NOT NULL,
		LIBNAME   VARCHAR2(50 BYTE)                   NOT NULL,
		TYPENAME  VARCHAR2(20 BYTE)                   NOT NULL,
		PDTYPE    VARCHAR2(20 BYTE),
		LIBSIZE   VARCHAR2(20 BYTE),
		STATE     VARCHAR2(20 BYTE)                   DEFAULT 'N' NOT NULL,
		ZIPID   VARCHAR2(22 BYTE),
		DELFLAG   CHAR(1 BYTE)                        DEFAULT 'N',
		CONSTRAINT LIBBATCHUPDATE_LIB_PK PRIMARY KEY(ID)
);

COMMENT ON TABLE LIBBATCHUPDATE_LIB IS 'LiveUpdate Detail';
COMMENT ON COLUMN LIBBATCHUPDATE_LIB.ID IS 'ID';
COMMENT ON COLUMN LIBBATCHUPDATE_LIB.LIBNAME IS '라이브러리 명';
COMMENT ON COLUMN LIBBATCHUPDATE_LIB.TYPENAME IS '타입 ( AD , CO, IM. API , AUTH )';
COMMENT ON COLUMN LIBBATCHUPDATE_LIB.PDTYPE IS '배포디렉토리';
COMMENT ON COLUMN LIBBATCHUPDATE_LIB.LIBSIZE IS '라이브러리 파일 크기';
COMMENT ON COLUMN LIBBATCHUPDATE_LIB.STATE IS '배포상태';
COMMENT ON COLUMN LIBBATCHUPDATE_LIB.ZIPID IS '압축파일ID';
COMMENT ON COLUMN LIBBATCHUPDATE_LIB.DELFLAG IS '삭제여부';

CREATE TABLE LIBBATCHUPDATE_DEPLOY (
		DEPLOYID  VARCHAR2(22 BYTE) NOT NULL,
		ZIPID   VARCHAR2(22 BYTE),
		REG_DT   VARCHAR2(30 BYTE) DEFAULT TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISSFF3'),
		CONSTRAINT LIBBATCHUPDATE_DEPLOY_PK PRIMARY KEY(DEPLOYID)
);
 
CREATE TABLE LIBBATCHUPDATE_STATUS (
		DEPLOYID  VARCHAR2(22 BYTE) NOT NULL,
		IM_NAME  VARCHAR2(50 BYTE)                    NOT NULL,
		STATE    VARCHAR2(20 BYTE)                    DEFAULT 'T' NOT NULL,
		REG_DT   VARCHAR2(30 BYTE)                    DEFAULT TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISSFF3'),
		ERR_LOG  CLOB,
		CONSTRAINT LIBBATCHUPDATE_STATUS_PK PRIMARY KEY(DEPLOYID, IM_NAME)
);

COMMENT ON TABLE LIBBATCHUPDATE_STATUS IS 'LiveUpdate Status';
COMMENT ON COLUMN LIBBATCHUPDATE_STATUS.DEPLOYID IS '압축파일ID';
COMMENT ON COLUMN LIBBATCHUPDATE_STATUS.IM_NAME IS 'IM 명';
COMMENT ON COLUMN LIBBATCHUPDATE_STATUS.STATE IS '상태';
COMMENT ON COLUMN LIBBATCHUPDATE_STATUS.REG_DT IS '등록일';

ALTER TABLE LIBBATCHUPDATE_ZIP ADD(
CHECKSUMSIZE VARCHAR(100),
DEPLOYTYPE VARCHAR(1)
);

ALTER TABLE LIBBATCHUPDATE_STATUS ADD (
 DEPLOYTYPE VARCHAR(1),
 IM_IP VARCHAR(20),
 START_DT VARCHAR(30),
 END_DT VARCHAR(30)
);
 
--WEB SERVICE TABLE
CREATE TABLE WS_SQLINFO (
		SQLID VARCHAR2(20) PRIMARY KEY NOT NULL,
		SQLNAME VARCHAR2(20),
		QUERYID VARCHAR2(20),
		ACTION VARCHAR2(20),
		DATASOURCEID VARCHAR2(20),
		SQLINFO VARCHAR2(200),
		OPERATIONID VARCHAR2(20),
		POSSESINSTITUTEID VARCHAR2(20),
		ADID VARCHAR2(50),
		GROUPID VARCHAR2(20) DEFAULT '',
		ADALIAS VARCHAR2(100)
);

COMMENT ON TABLE WS_SQLINFO IS '웹서비스_SQL정보'; 
COMMENT ON COLUMN WS_SQLINFO.SQLID IS 'SQL_ID';
COMMENT ON COLUMN WS_SQLINFO.SQLNAME IS 'SQL명';
COMMENT ON COLUMN WS_SQLINFO.QUERYID IS '쿼리ID';
COMMENT ON COLUMN WS_SQLINFO.ACTION IS '액션';
COMMENT ON COLUMN WS_SQLINFO.DATASOURCEID IS '데이터소스ID';
COMMENT ON COLUMN WS_SQLINFO.SQLINFO IS 'SQL정보';
COMMENT ON COLUMN WS_SQLINFO.OPERATIONID IS '오퍼레이션ID';
COMMENT ON COLUMN WS_SQLINFO.POSSESINSTITUTEID IS '보유기관ID';

CREATE TABLE WS_INSTITUTEINFO (
		INSTITUTEID VARCHAR2(20) PRIMARY KEY NOT NULL,
		INSTITUTENAME VARCHAR2(20),
		DEPTNAME VARCHAR2(20),
		CHARGER VARCHAR2 (20),
		CHARGERNUMBER VARCHAR2(30),
		INSTITUTEINFO VARCHAR2(200)
);

COMMENT ON TABLE WS_INSTITUTEINFO IS '웹서비스_기관정보'; 
COMMENT ON COLUMN WS_INSTITUTEINFO.INSTITUTEID IS '기관ID';
COMMENT ON COLUMN WS_INSTITUTEINFO.INSTITUTENAME IS '기관명';
COMMENT ON COLUMN WS_INSTITUTEINFO.DEPTNAME IS '부서명';
COMMENT ON COLUMN WS_INSTITUTEINFO.CHARGER IS '담당자';
COMMENT ON COLUMN WS_INSTITUTEINFO.CHARGERNUMBER IS '담당자연락처';
COMMENT ON COLUMN WS_INSTITUTEINFO.INSTITUTEINFO IS '기관정보';
 
CREATE TABLE WS_POSSESINSTITUTEINFO (
		POSSESINSTITUTEID VARCHAR2(20) PRIMARY KEY NOT NULL,
		INSTITUTEIP VARCHAR2(20),
		INSTITUTEPORT VARCHAR2(20),
		POSSESREGDATE DATE
);

COMMENT ON TABLE WS_POSSESINSTITUTEINFO IS '웹서비스_보유기관정보'; 
COMMENT ON COLUMN WS_POSSESINSTITUTEINFO.POSSESINSTITUTEID IS '보유기관ID';
COMMENT ON COLUMN WS_POSSESINSTITUTEINFO.INSTITUTEIP IS '기관IP';
COMMENT ON COLUMN WS_POSSESINSTITUTEINFO.INSTITUTEPORT IS '기관PORT';
COMMENT ON COLUMN WS_POSSESINSTITUTEINFO.POSSESREGDATE IS '보유기관등록일';
 
CREATE TABLE WS_INSTITUTEUSE (
		USEINSTITUTEID VARCHAR2(20)  PRIMARY KEY NOT NULL,
		USEREGDATE DATE,
		USEIPLIST VARCHAR2(20)
);

COMMENT ON COLUMN WS_INSTITUTEUSE.USEIPLIST IS'이용기관IP';
COMMENT ON COLUMN WS_INSTITUTEUSE.USEINSTITUTEID IS '이용기관ID';
COMMENT ON COLUMN WS_INSTITUTEUSE.USEREGDATE IS '이용기관등록일';
COMMENT ON TABLE WS_INSTITUTEUSE IS '웹서비스_이용기관정보'; 

CREATE TABLE WS_INSTITUTEUSESQL (
		USEINSTITUTEID VARCHAR2(20)  NOT NULL,
		SQLID VARCHAR2(20)   NOT NULL,
		SQLUSEYN VARCHAR2(1),
		SQLREGDATE DATE,
		INTERFACEID VARCHAR2(100),
		CONSTRAINT WS_INSTITUTEUSESQL_PK PRIMARY KEY(INTERFACEID)
);

COMMENT ON TABLE WS_INSTITUTEUSESQL IS '웹서비스_이용기관사용쿼리';
COMMENT ON COLUMN WS_INSTITUTEUSESQL.USEINSTITUTEID IS '이용기관ID';
COMMENT ON COLUMN WS_INSTITUTEUSESQL.SQLID IS 'SQL_ID';
COMMENT ON COLUMN WS_INSTITUTEUSESQL.SQLUSEYN IS '쿼리사용가능여부';
COMMENT ON COLUMN WS_INSTITUTEUSESQL.SQLREGDATE IS '쿼리사용시작일';
COMMENT ON COLUMN WS_INSTITUTEUSESQL.INTERFACEID IS '인터페이스ID';

CREATE TABLE WS_LOGGING (	
		TRANSACTIONID VARCHAR2(30), 
		INTERFACEID VARCHAR2(30), 
		LOGDATE DATE DEFAULT sysdate, 
		POSITION VARCHAR2(1), 
		STATE VARCHAR2(1), 
		MESSAGE VARCHAR2(2000), 
		MESSAGESIZE NUMBER, 
		CONSTRAINT WS_LOGGING_PK PRIMARY KEY(TRANSACTIONID, POSITION)
);

-- IM/AD ResourceInfo 테이블
CREATE TABLE ESB_MONITOR_RESOURCE (
	MO_ID VARCHAR2(22) NOT NULL,
	MO_TYPE VARCHAR2(3) NOT NULL,
 	PD_ID VARCHAR2(22) NOT NULL,
	CPU_USE VARCHAR2(5),
  	JVM_USE VARCHAR2(5),
	DISK_USE VARCHAR2(5),
	MO_REG_DATE VARCHAR2(14) NOT NULL, 
	CONSTRAINT ESB_MONITOR_RESOURCE_PK PRIMARY KEY(MO_ID)
);

-- ESB Resource Info 테이블
CREATE TABLE INDIGO_RESOURCE (
	MO_ID VARCHAR2(22) NOT NULL,
	HA_NAME VARCHAR2(22) NOT NULL,
	CPU_USE VARCHAR2(4),
  	MEM_USE VARCHAR2(4),
 	JVM_USE VARCHAR2(4),
	DISK_USE VARCHAR2(4),	
 	DISK_NAME VARCHAR2(20),
  	BR_STORE VARCHAR2(4),
  	BR_MEM VARCHAR2(4),
  	BR_TEMP VARCHAR2(4),  
	MO_REG_DATE VARCHAR2(14) NOT NULL, 
	CONSTRAINT INDIGO_RESOURCE_PK PRIMARY KEY(MO_ID)
);

-- ESB Queue Info 테이블
CREATE TABLE INDIGO_QUEUE (
	MO_ID VARCHAR2(22) NOT NULL,
	HA_NAME VARCHAR2(22) NOT NULL,
  	Q_NAME VARCHAR2(20) NOT NULL,
  	Q_MEM  VARCHAR2(4),
 	Q_SIZE NUMBER,
  	Q_CONSUMER NUMBER,
	MO_REG_DATE VARCHAR2(14) NOT NULL, 
	CONSTRAINT INDIGO_QUEUE_PK PRIMARY KEY(MO_ID)
);

-- ESB 컴포넌트 정보 테이블
CREATE TABLE INDIGO_COMPONENT (
	MO_ID VARCHAR2(22) NOT NULL,
	HA_NAME VARCHAR2(22) NOT NULL,
	COMP_TYPE VARCHAR2(9) NOT NULL,
	COMP_NAME VARCHAR2(50),
	COMP_STATUS CHAR,
	MO_REG_DATE VARCHAR2(14),
	CONSTRAINT INDIGO_COMPONENT_PK PRIMARY KEY(MO_ID)
);

COMMENT ON TABLE ESB_MONITOR_RESOURCE IS 'IM/AD 리소스정보테이블';
COMMENT ON TABLE INDIGO_RESOURCE IS 'ESB 리소스 정보 테이블';
COMMENT ON TABLE INDIGO_QUEUE IS 'ESB 큐 정보 테이블';
COMMENT ON TABLE INDIGO_COMPONENT IS 'ESB 컴포넌트 정보 테이블';

-- 리소스사용량 컬럼크기 변경 4->5
ALTER TABLE INDIGO_RESOURCE
MODIFY (
  CPU_USE VARCHAR2(5),
  MEM_USE VARCHAR2(5),
  JVM_USE VARCHAR2(5),
  DISK_USE VARCHAR2(5),
  BR_STORE VARCHAR2(5),
  BR_MEM VARCHAR2(5),
  BR_TEMP VARCHAR2(5)
);

/* 공통리소스 관리 */
CREATE TABLE INDIGO_CMM_RESOURCE (
  RESOURCE_KEY      VARCHAR2(30)      NOT NULL PRIMARY KEY , 
  RESOURCE_TYPE     VARCHAR2(255)      NOT NULL, 
  RESOURCE_ID       VARCHAR2(255)      NOT NULL, 
  RESOURCE_ALIAS    VARCHAR2(255)      NOT NULL,
  RESOURCE_USER    VARCHAR2(255)      NOT NULL,
  RESOURCE_MEMO     VARCHAR2(4000)         NULL,
  RESOURCE_DATE VARCHAR2(30) DEFAULT TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISSFF3')  
);

COMMENT ON TABLE INDIGO_CMM_RESOURCE IS '공통리소스 일반정보테이블';
COMMENT ON COLUMN INDIGO_CMM_RESOURCE.RESOURCE_KEY IS '일반정보 테이블 KEY';
COMMENT ON COLUMN INDIGO_CMM_RESOURCE.RESOURCE_TYPE IS '리소스 타입(DB, JMS)';
COMMENT ON COLUMN INDIGO_CMM_RESOURCE.RESOURCE_ID IS '리소스 아이디';
COMMENT ON COLUMN INDIGO_CMM_RESOURCE.RESOURCE_ALIAS IS '리소스 명';
COMMENT ON COLUMN INDIGO_CMM_RESOURCE.RESOURCE_USER IS '리소스 등록자';
COMMENT ON COLUMN INDIGO_CMM_RESOURCE.RESOURCE_MEMO IS '리소스 메모';
COMMENT ON COLUMN INDIGO_CMM_RESOURCE.RESOURCE_DATE IS '리소스 저장날짜';

CREATE TABLE INDIGO_CMM_RESOURCE_PROPERTY (
  RESOURCE_PROPERTY_KEY      VARCHAR2(30)     NOT NULL PRIMARY KEY, 
  RESOURCE_PROPERTY_NAME     VARCHAR2(255)     NOT NULL, 
  RESOURCE_PROPERTY_VALUE    VARCHAR2(4000)     NOT NULL, 
  RESOURCE_KEY               VARCHAR2(30)         NULL
);

COMMENT ON TABLE INDIGO_CMM_RESOURCE_PROPERTY IS '공통리소스 상세설정정보테이블';
COMMENT ON COLUMN INDIGO_CMM_RESOURCE_PROPERTY.RESOURCE_PROPERTY_KEY IS '설정 프로퍼티 KEY';
COMMENT ON COLUMN INDIGO_CMM_RESOURCE_PROPERTY.RESOURCE_PROPERTY_NAME IS '설정 프로퍼티 이름';
COMMENT ON COLUMN INDIGO_CMM_RESOURCE_PROPERTY.RESOURCE_PROPERTY_VALUE IS '설정 프로퍼티 값';
COMMENT ON COLUMN INDIGO_CMM_RESOURCE_PROPERTY.RESOURCE_KEY IS '일반정보 테이블 KEY';

CREATE TABLE INDIGO_CMM_RESOURCE_MAPPING (
  RESOURCE_MAPPING_KEY    VARCHAR2(30)     NOT NULL PRIMARY KEY, 
  RESOURCE_KEY            VARCHAR2(30)         NULL, 
  IN_ID                   VARCHAR2(22)         NULL, 
  MAPPING_DATE           VARCHAR2(30) DEFAULT TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISSFF3')
);

COMMENT ON TABLE INDIGO_CMM_RESOURCE_MAPPING IS '공통리소스 - Adaptor 매핑정보테이블';
COMMENT ON COLUMN INDIGO_CMM_RESOURCE_MAPPING.RESOURCE_MAPPING_KEY IS '매핑 KEY';
COMMENT ON COLUMN INDIGO_CMM_RESOURCE_MAPPING.RESOURCE_KEY IS '일반정보 테이블 KEY';
COMMENT ON COLUMN INDIGO_CMM_RESOURCE_MAPPING.IN_ID IS '어댑터 아이디';
COMMENT ON COLUMN INDIGO_CMM_RESOURCE_MAPPING.MAPPING_DATE IS '매핑 날짜';

/* 설정 히스토리 관리 */
CREATE TABLE INDIGO_CMM_RESOURCE_HISTORY (
  HISTORY_ID            VARCHAR2(255)     NOT NULL, 
  HISTORY_FILE_CONTS    BLOB                  NULL, 
  HISTORY_FILE_SIZE     VARCHAR2(255)         NULL, 
  HISTORY_DATE          VARCHAR2(30)      DEFAULT TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISSFF3')      NOT NULL, 
  USE_DATAYN            VARCHAR2(1)       NOT NULL,
  HISTORY_VERSION		number       NOT NULL,
  HISTORY_MEMO			VARCHAR2(4000)
);

COMMENT ON TABLE INDIGO_CMM_RESOURCE_HISTORY IS '설정파일 이력관리테이블';
COMMENT ON COLUMN INDIGO_CMM_RESOURCE_HISTORY.HISTORY_ID IS '이력 아이디';
COMMENT ON COLUMN INDIGO_CMM_RESOURCE_HISTORY.HISTORY_FILE_CONTS IS '설정파일';
COMMENT ON COLUMN INDIGO_CMM_RESOURCE_HISTORY.HISTORY_FILE_SIZE IS '설정파일 사이즈';
COMMENT ON COLUMN INDIGO_CMM_RESOURCE_HISTORY.HISTORY_DATE IS '이력 날짜';
COMMENT ON COLUMN INDIGO_CMM_RESOURCE_HISTORY.USE_DATAYN IS '사용유무(Y, N)';
COMMENT ON COLUMN INDIGO_CMM_RESOURCE_HISTORY.HISTORY_VERSION IS '이력 버전';
COMMENT ON COLUMN INDIGO_CMM_RESOURCE_HISTORY.HISTORY_MEMO IS '이력 메모';


ALTER TABLE INDIGO_CMM_RESOURCE_HISTORY ADD PRIMARY KEY(HISTORY_ID, HISTORY_DATE);
ALTER TABLE ESB_INSTANCE_FILE ADD(HISTORY_ID VARCHAR2(255));

-- 변경된 IMS테이블 컬럼 추가
ALTER TABLE IMS_MSG_HUB_DETAIL_LOG ADD MSG_SIZE NUMBER;
ALTER TABLE IMS_MSG_HUB_DETAIL_LOG ADD SND_MSG BLOB;

ALTER TABLE IMS_MSG_HUB_MASTER_LOG ADD MSG_SIZE NUMBER;
ALTER TABLE IMS_MSG_HUB_MASTER_LOG ADD ESB_HOST VARCHAR(255);

ALTER TABLE IMS_MSG_HUB_RESULT_LOG ADD MSG_SIZE NUMBER;
ALTER TABLE IMS_MSG_HUB_RESULT_LOG ADD RETRY_CNT NUMBER;

/* 메시지 기능 개발로 인한 테이블 생성 2016.05.19 작성자 : 장준환 */

CREATE TABLE MESSAGE_INFO(
    MESSAGE_ID VARCHAR(255) PRIMARY KEY NOT NULL,
    MESSAGE_NAME VARCHAR(255) NOT NULL,
    MESSAGE_TYPE VARCHAR(255) NOT NULL,
    MESSAGE_MEMO VARCHAR(255) NULL
);

CREATE TABLE DB_MESSAGE(
    MESSAGE_ID VARCHAR(255) NOT NULL  PRIMARY KEY  REFERENCES MESSAGE_INFO(MESSAGE_ID),
    CONNECTION_URL VARCHAR(255) NULL,
    CONNECTION_NAME VARCHAR(255) NULL,
    CONNECTION_PWD VARCHAR(255) NULL
);

CREATE TABLE DB_TABLE(
    TABLE_ID VARCHAR(255) NOT NULL PRIMARY KEY ,
    MESSAGE_ID VARCHAR(255) NOT NULL REFERENCES DB_MESSAGE(MESSAGE_ID),
    TABLE_NAME VARCHAR(255) NULL,
    PARENT_TABLE VARCHAR(255) NULL,
    ROOT VARCHAR(255) NULL
 );
 
CREATE SEQUENCE COLUMNNUM_SEQUENCE START WITH 1 INCREMENT BY 1 MAXVALUE 10000;

CREATE TABLE DB_COLUMN(
    COLUMN_ID NUMBER NOT NULL  PRIMARY KEY,
    TABLE_ID VARCHAR(255) NOT NULL  REFERENCES DB_TABLE(TABLE_ID),
    COLUMN_NAME VARCHAR(255) NOT NULL,
    COLUMN_TYPE VARCHAR(255) NOT NULL,
    COLUMN_ALIAS VARCHAR(255) NOT NULL
);

-- 인터페이스 정보 테이블

CREATE TABLE INTERFACE_INFO 
  (IF_ID VARCHAR2(255) PRIMARY KEY, 
  IF_NAME VARCHAR2(255), 
  LINKAGE_PATTERN VARCHAR2(255), 
  MANAGER VARCHAR2(255), 
  USE_CASE CHAR(1));
 

-- 기관 정보 테이블

CREATE TABLE INSTITUTE_INFO
   (	
    INS_CODE VARCHAR2(255 BYTE) NOT NULL PRIMARY KEY, 
	INS_NAME VARCHAR2(255 BYTE) NOT NULL,
	INS_MANAGER VARCHAR2(255 BYTE), 
	INS_CONTACT VARCHAR2(255 BYTE), 
	INS_EMAIL VARCHAR2(255 BYTE), 
	INS_MEMO VARCHAR2(255 BYTE)
   );
   
-- 매핑 테이블

CREATE TABLE MAPPING
  (
    MAPPING_CODE VARCHAR2(255), 
	IF_ID VARCHAR2(255), 
	INS_CODE VARCHAR2(255), 
	TR_TYPE VARCHAR2(20) DEFAULT 'SND', 
	MESSAGE_ID VARCHAR2(255) DEFAULT 'DEF_MSG_ID',
	MAPPING_USE_CASE CHAR(1) DEFAULT 'Y'
   );
   
CREATE UNIQUE INDEX MAPPING_PK ON MAPPING (MAPPING_CODE);

  ALTER TABLE "MAPPING" ADD CONSTRAINT "MAPPING_FK1" FOREIGN KEY ("IF_ID")
	  REFERENCES "INTERFACE_INFO" ("IF_ID") ENABLE;
  ALTER TABLE "MAPPING" ADD CONSTRAINT "MAPPING_FK2" FOREIGN KEY ("INS_CODE")
	  REFERENCES "INSTITUTE_INFO" ("INS_CODE") ENABLE;
  ALTER TABLE "MAPPING" ADD CONSTRAINT "MAPPING_FK3" FOREIGN KEY ("MESSAGE_ID")
	  REFERENCES "MESSAGE_INFO" ("MESSAGE_ID") ENABLE;

-- 2016-10-10 JunHo Kim    master_log table index

CREATE INDEX IMS_MSG_HUB_MASTER_LOG_INDEX1 ON IMS_MSG_HUB_MASTER_LOG (
		MSG_CREATE_DT
);

-- 2017-08-01 Dain Jin     created additional columns on indigo_user

ALTER TABLE INDIGO_USER ADD(PW_LAST_CHANGE_DTTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL); 
ALTER TABLE INDIGO_USER ADD(PW_ERR_CNT INTEGER DEFAULT 0 NOT NULL);
ALTER TABLE INDIGO_USER ADD(USER_STATUS CHAR(1) DEFAULT 'A' NOT NULL);
ALTER TABLE INDIGO_USER ADD(ALLOWED_TML_IP VARCHAR(512));

-- 2017-08-09 Dain Jin		created user-interface mapping info table and set admin to have no restrictions on it.
-- 2018-06-05 Dain Jin		changed foreign key reference of USER_IF_MAPP_INFO.USER_ID from INDIGO_USER.USER_ID to INDIGO_GROUP.GROUP_ID 

CREATE TABLE USER_IF_MAPP_INFO (
	MAPP_ID VARCHAR(22) PRIMARY KEY,
	USER_ID VARCHAR(22) NOT NULL REFERENCES INDIGO_GROUP(GROUP_ID),
	IF_ID VARCHAR(64) NOT NULL
);

CREATE TABLE ESB_NOTICE 
(
  ID NUMBER(10, 0) PRIMARY KEY
, CONTS VARCHAR2(2000 BYTE) 
, REG_DATE CHAR(17 BYTE) 
);



CREATE TABLE ESB_NOTIFY_MESSAGE 
(
  MESSAGE_ID VARCHAR2(60 BYTE) PRIMARY KEY 
, MESSAGE_STATUS CHAR(1 BYTE) 
, COMPONENT_NAME VARCHAR2(255 BYTE) 
, CREATE_DATE DATE 
, DONE_YN CHAR(1 BYTE) DEFAULT 'N' 
, DONE_DATE DATE 
, MESSAGE_CONTENT VARCHAR2(4000 BYTE) 
);

-- 템플릿 이력 테이블 송신 메시지 컬럼 추가
ALTER TABLE ESB_TEMP_IF_DEST_LOG ADD SEND_MESSAGE VARCHAR2(4000);


-- 모델러 상세 이력

-- 트레이스 테이블
CREATE TABLE INDIGO_MESSAGETRACED 
(
  ID NUMBER NOT NULL 
, PROPERTIES CLOB 
, TIMESTAMP TIMESTAMP(6) 
, HEADERS CLOB 
, EXCHANGEID VARCHAR2(255 BYTE) 
, BODY CLOB 
, EXCHANGEPATTERN VARCHAR2(255 BYTE) 
, ROUTEID VARCHAR2(255 BYTE) 
, FROMENDPOINTURI VARCHAR2(255 BYTE) 
, PREVIOUSNODE VARCHAR2(255 BYTE) 
, TONODE VARCHAR2(255 BYTE) 
, SHORTEXCHANGEID VARCHAR2(255 BYTE) 
, BODYTYPE VARCHAR2(255 BYTE) 
, OUTBODY CLOB 
, OUTBODYTYPE VARCHAR2(255 BYTE) 
, OUTHEADERS CLOB 
, CAUSEDBYEXCEPTION CLOB 
, INOUT VARCHAR2(3 BYTE) 
, STATUS CHAR(1 BYTE) 
, NODEID VARCHAR2(60 BYTE) 
, GROUPEXCHANGEID VARCHAR2(255 BYTE) 
, TX_ID VARCHAR2(60 BYTE) 
, RETRY_COUNT NUMBER 
, PREVIOUSNODEID VARCHAR2(20 BYTE) 
); 

CREATE INDEX INDIGO_MESSAGETRACED_INDEX1 ON INDIGO_MESSAGETRACED (TX_ID);
CREATE INDEX INDIGO_MESSAGETRACED_INDEX2 ON INDIGO_MESSAGETRACED (GROUPEXCHANGEID);

CREATE SEQUENCE INDIGO_TRACE_SEQUENCE;

-- 모델러 프로젝트 테이블
CREATE TABLE INDIGO_MODELERPROJECT(
	 PROJECTID VARCHAR2(20) NOT NULL PRIMARY KEY,
	 PROJECTNAME VARCHAR2(30),
	 JSONTEXT BLOB,
	 BEANTEXT BLOB,
	 INFO VARCHAR2(4000),
	 USERID VARCHAR2(30),
	 TIMESTAMP TIMESTAMP(6),
	 FD_ID VARCHAR2(20),
	 PROJECTALIAS VARCHAR2(256)
);

-- 뉴템플릿 이력 MASTER 테이블
CREATE TABLE ESB_TEMP_IF_MASTER_LOG
(	IF_ID VARCHAR2(40) NOT NULL, 
	TX_ID VARCHAR2(64) NOT NULL, 
	TX_COUNT NUMBER(8,0), 
	TX_PROPERTY VARCHAR2(4000), 
	TX_START_DATE VARCHAR2(17), 
	TX_HUB_RCV_DATE VARCHAR2(17), 
	ESB_HOST VARCHAR2(255),
  CONSTRAINT M_LOG_PK PRIMARY KEY (IF_ID, TX_ID)
);

CREATE INDEX IDX_TX_START_DATE ON ESB_TEMP_IF_MASTER_LOG (
		TX_START_DATE
);

-- 뉴템플릿 이력 DETAIL 테이블
CREATE TABLE ESB_TEMP_IF_DEST_LOG 
(	TX_ID VARCHAR2(64) NOT NULL, 
	DEST_ID VARCHAR2(30) NOT NULL, 
	DEST_RCV_DATE VARCHAR2(17), 
	DEST_RESULT CHAR(1), 
	RESULT_MESSAGE VARCHAR2(4000), 
	REACTION_CNT NUMBER(4,0), 
	REACTION_DATE VARCHAR2(17), 
	DEST_ERROR_COUNT NUMBER(8,0), 
	SEND_MESSAGE VARCHAR2(4000), 
	 CONSTRAINT D_LOG_PK PRIMARY KEY (TX_ID, DEST_ID)
);

CREATE INDEX IDX_DEST_RCV_DATE ON ESB_TEMP_IF_DEST_LOG (
		DEST_RCV_DATE
);

-- 뉴템플릿 송신 인터페이스 테이블
CREATE TABLE ESB_TEMP_IF_MASTER 
(	IF_ID VARCHAR2(40), 
	IF_NAME VARCHAR2(100), 
	IF_TYPE VARCHAR2(20), 
	SYSTEM_ID VARCHAR2(20), 
	SYSTEM_NAME VARCHAR2(64), 
	ROUTE_SEND_Q VARCHAR2(40), 
	TARGET_LISTEN_Q VARCHAR2(40), 
	ROUTE_RESULT_Q VARCHAR2(40), 
	SOURCE_LISTEN_Q VARCHAR2(40), 
	DESCRIPTION VARCHAR2(4000), 
	REG_DATE VARCHAR2(17), 
	MOD_DATE VARCHAR2(17), 
	USE_YN CHAR(1), 
	 PRIMARY KEY (IF_ID)
);

-- 뉴템플릿 수신 인터페이스 테이블
CREATE TABLE ESB_TEMP_IF_DEST 
(	IF_ID VARCHAR2(40) NOT NULL, 
	DEST_ID VARCHAR2(10) NOT NULL, 
	IF_TYPE VARCHAR2(20), 
	SYSTEM_ID VARCHAR2(20), 
	SYSTEM_NAME VARCHAR2(64), 
	DESCRIPTION VARCHAR2(4000), 
	REG_DATE VARCHAR2(17), 
	MOD_DATE VARCHAR2(17), 
	 CONSTRAINT UNIQUE_PK PRIMARY KEY (IF_ID, DEST_ID)
);

COMMIT;