DROP TABLE ADT_SA;
DROP TABLE ADT_SU;
DROP TABLE ADT_ENDPOINT;
DROP TABLE ADT_MESSAGE_EXCHANGE;
DROP TABLE ADT_INSTANCE_SA;

CREATE TABLE ADT_SA
(
  ID_SA        VARCHAR(50) PRIMARY KEY,
  SA_NAME         VARCHAR(100),
  DESCRIPTION  VARCHAR(100),
  UNIT_COUNT   INTEGER
);

CREATE TABLE ADT_SU
(
  ID_SU           VARCHAR(50)             NOT NULL PRIMARY KEY,
  ID_SA           VARCHAR(50)             NOT NULL,
  SU_NAME            VARCHAR(100)            NOT NULL,
  COMPONENT_NAME  VARCHAR(100)            NOT NULL
);

CREATE TABLE ADT_ENDPOINT
(
  ID_ENDPOINT     VARCHAR(50)             NOT NULL PRIMARY KEY,
  ID_SU           VARCHAR(50)             NOT NULL,
  SERVICE_NAME    VARCHAR(48)             NOT NULL,
  INTERFACE_NAME  VARCHAR(48),
  ENDPOINT_NAME   VARCHAR(60)             NOT NULL,
  NAMESPACE       VARCHAR(100)            NOT NULL,
  TYPE            VARCHAR(48)             NOT NULL,
  COMPONENT_NAME  VARCHAR(48)             NOT NULL,
  FINAL_YN        VARCHAR(1)
);

CREATE TABLE ADT_MESSAGE_EXCHANGE
(
  ID_ME               VARCHAR(50)         NOT NULL PRIMARY KEY,
  ID_ENDPOINT_SOURCE  VARCHAR(50)         NOT NULL,
  ID_ENDPOINT_TARGET  VARCHAR(50)         NOT NULL,
  ID_INSTANCE_SA      VARCHAR(50)         NOT NULL,
  ID                  VARCHAR(100)        NOT NULL,
  PATTERN             VARCHAR(48)         NOT NULL,
  STATE               VARCHAR(48)         NOT NULL,
  ME_DATE             TIMESTAMP             NOT NULL,
  MESSAGE             BLOB,
  MSG_IN              BLOB,
  MSG_OUT             BLOB,
  MSG_FAULT           BLOB
);

CREATE TABLE ADT_INSTANCE_SA
(
  ID_INSTANCE_SA  VARCHAR(50)             NOT NULL PRIMARY KEY,
  ID_SA           VARCHAR(50)             NOT NULL,
  START_DATE      TIMESTAMP                  NOT NULL,
  END_DATE        TIMESTAMP                 NOT NULL,
  STATE           VARCHAR(48)             NOT NULL,
  CORRELATIONID   VARCHAR(100)            NOT NULL,
  TX_ID           VARCHAR(50)
);
