DROP TABLE ADT_SA;
DROP TABLE ADT_SU;
DROP TABLE ADT_ENDPOINT;
DROP TABLE ADT_MESSAGE_EXCHANGE;
DROP TABLE ADT_INSTANCE_SA;

CREATE TABLE ADT_SA
(
  ID_SA        VARCHAR2(50 BYTE),
  SA_NAME         VARCHAR2(100 BYTE),
  DESCRIPTION  VARCHAR2(100 BYTE),
  UNIT_COUNT   NUMBER
);
ALTER TABLE ADT_SA ADD (
  CONSTRAINT PK_SA PRIMARY KEY (ID_SA));

CREATE TABLE ADT_SU
(
  ID_SU           VARCHAR2(50 BYTE)             NOT NULL,
  ID_SA           VARCHAR2(50 BYTE)             NOT NULL,
  SU_NAME            VARCHAR2(100 BYTE)            NOT NULL,
  COMPONENT_NAME  VARCHAR2(100 BYTE)            NOT NULL
);
ALTER TABLE ADT_SU ADD (
  PRIMARY KEY (ID_SU));
  
CREATE TABLE ADT_ENDPOINT
(
  ID_ENDPOINT     VARCHAR2(50 BYTE)             NOT NULL,
  ID_SU           VARCHAR2(50 BYTE)             NOT NULL,
  SERVICE_NAME    VARCHAR2(48 BYTE)             NOT NULL,
  INTERFACE_NAME  VARCHAR2(48 BYTE),
  ENDPOINT_NAME   VARCHAR2(60 BYTE)             NOT NULL,
  NAMESPACE       VARCHAR2(100 BYTE)            NOT NULL,
  TYPE            VARCHAR2(48 BYTE)             NOT NULL,
  COMPONENT_NAME  VARCHAR2(48 BYTE)             NOT NULL,
  FINAL_YN        VARCHAR2(1 BYTE)
);
ALTER TABLE ADT_ENDPOINT ADD (
  PRIMARY KEY (ID_ENDPOINT));

CREATE TABLE ADT_MESSAGE_EXCHANGE
(
  ID_ME               VARCHAR2(50 BYTE)         NOT NULL,
  ID_ENDPOINT_SOURCE  VARCHAR2(50 BYTE)         NOT NULL,
  ID_ENDPOINT_TARGET  VARCHAR2(50 BYTE)         NOT NULL,
  ID_INSTANCE_SA      VARCHAR2(50 BYTE)         NOT NULL,
  ID                  VARCHAR2(100 BYTE)        NOT NULL,
  PATTERN             VARCHAR2(48 BYTE)         NOT NULL,
  STATE               VARCHAR2(48 BYTE)         NOT NULL,
  ME_DATE             TIMESTAMP(6)              NOT NULL,
  MESSAGE             BLOB,
  MSG_IN              BLOB,
  MSG_OUT             BLOB,
  MSG_FAULT           BLOB
);
ALTER TABLE ADT_MESSAGE_EXCHANGE ADD (
  PRIMARY KEY (ID_ME));
  
CREATE TABLE ADT_INSTANCE_SA
(
  ID_INSTANCE_SA  VARCHAR2(50 BYTE)             NOT NULL,
  ID_SA           VARCHAR2(50 BYTE)             NOT NULL,
  START_DATE      TIMESTAMP(6)                  NOT NULL,
  END_DATE        TIMESTAMP(6)                  NOT NULL,
  STATE           VARCHAR2(48 BYTE)             NOT NULL,
  CORRELATIONID   VARCHAR2(100 BYTE)            NOT NULL,
  TX_ID           VARCHAR2(50 BYTE)
);
ALTER TABLE ADT_INSTANCE_SA ADD (
  PRIMARY KEY (ID_INSTANCE_SA));
