DROP TABLE MCI_ONLINE_LOG;

DROP TABLE MCI_SCHEDULER;

DROP TABLE MCI_ERROR_LOG;

DROP TABLE MCI_FTP_LOG;

DROP TABLE MCI_MSG_INFOMATION;

DROP TABLE MCI_MSG_MAPPING;


CREATE TABLE MCI_ONLINE_LOG
(
  ADAPTOR_NAME  VARCHAR(30)               NOT NULL,
  LOG_TIME      VARCHAR(17)               NOT NULL,
  TRAN_CODE     VARCHAR(15),
  COMM_TYPE     VARCHAR(3),
  COMM_OP       CHAR(1),
  INOUT_FLAG    CHAR(1),
  TRAN_SEQ      VARCHAR(40),
  TRAN_DATA     BLOB,
  STATUS        CHAR(1),
  ERRMSG        VARCHAR(200)
);

CREATE INDEX IDX_LOG_TIME ON MCI_ONLINE_LOG
(LOG_TIME);

CREATE TABLE MCI_SCHEDULER
(
  SCHE_NAME     CHAR(25)                   NOT NULL PRIMARY KEY,
  CRONTAB       VARCHAR(25),
  ADAPTOR_NAME  VARCHAR(30),
  SCHE_DESC     VARCHAR(100),
  SCHE_FILE     VARCHAR(50),
  SCHE_DATE     VARCHAR(20),
  REPEAT        CHAR(1),
  ACTIVE        VARCHAR(3),
  ETC           VARCHAR(100)
);

 CREATE TABLE MCI_ERROR_LOG
(
  ADAPTOR_NAME  VARCHAR(30)               NOT NULL,
  LOG_TIME      VARCHAR(17)               NOT NULL,
  COMM_TYPE     VARCHAR(3),
  COMM_OP       CHAR(1),
  INOUT_FLAG    CHAR(1),
  ERR_MSG       VARCHAR(4000)
);

CREATE INDEX IDX_ERR_LOG_TIME ON MCI_ERROR_LOG
(ADAPTOR_NAME, LOG_TIME);

CREATE TABLE MCI_FTP_LOG
(
  ADAPTOR_NAME  VARCHAR(30)               NOT NULL,
  TRAN_STIME    DATE,
  TRAN_ETIME    DATE,
  FILE_NAME     VARCHAR(30),
  TOTAL_SIZE    INTEGER,
  CUR_SIZE      INTEGER,
  TRAN_STATUS   CHAR(1),
  INOUT_FLAG    CHAR(1),
  ERROR_CODE    VARCHAR(20),
  ERROR_MSG     VARCHAR(200),
  STD_DATE      VARCHAR(20),
  TRAN_ID       VARCHAR(30),
  START_YN      CHAR(1),
  FILE_PATH     VARCHAR(100)
);

CREATE INDEX IDX_FTP_LOG_TIME ON MCI_FTP_LOG
(ADAPTOR_NAME, TRAN_STIME);

CREATE TABLE MCI_MSG_INFOMATION (
  AGENT_NAME          VARCHAR(60)      NOT NULL, 
  TRAN_CODE           VARCHAR(40)      NOT NULL, 
  TRAN_DIRECTION      CHAR(1)          NOT NULL, 
  TRAN_MODE           CHAR(1)          NOT NULL, 
  CHN_TRAN_CODE       VARCHAR(40)              , 
  REDIR_AGENT_NAME    VARCHAR(60)      NOT NULL, 
  IN_TYPE             VARCHAR(10)      NOT NULL, 
  OUT_TYPE            VARCHAR(10)      NOT NULL, 
  SERVICE_NAME        VARCHAR(20)              , 
  TRAN_COMMENT        VARCHAR(200)             , 
  RESERVE             VARCHAR(40)         
);

ALTER TABLE MCI_MSG_INFOMATION ADD
    CONSTRAINT PK_MCI_MSG_INFOMATION
    PRIMARY KEY ( AGENT_NAME, TRAN_CODE, TRAN_DIRECTION, TRAN_MODE );

CREATE TABLE MCI_MSG_MAPPING (
  AGENT_NAME        VARCHAR(60)      NOT NULL, 
  TRAN_CODE         VARCHAR(40)      NOT NULL, 
  TRAN_DIRECTION    CHAR(1)           NOT NULL, 
  TRAN_MODE         CHAR(1)           NOT NULL, 
  MAPPING_TYPE      VARCHAR(4)       NOT NULL, 
  "NO"              INTEGER         NOT NULL, 
  DIVISION          CHAR(1)               , 
  NAME_KOR          VARCHAR(60)          , 
  NAME              VARCHAR(60)          , 
  RANK              VARCHAR(20)          , 
  TYPE              VARCHAR(10)         , 
  LENGTH            INTEGER        DEFAULT 0             , 
  CHILD_COUNT       INTEGER       DEFAULT 0             , 
  COUNT_NO          INTEGER       DEFAULT 0             , 
  REQURED           CHAR(1)          DEFAULT 'N'            , 
 "FUNCTION"          VARCHAR(100)         , 
  DEFAULT_VAL       VARCHAR(100)         
);
ALTER TABLE MCI_MSG_MAPPING ADD
    CONSTRAINT PK_MCI_MSG_MAPPING_RECORD
    PRIMARY KEY ( AGENT_NAME, TRAN_CODE, TRAN_DIRECTION, TRAN_MODE, MAPPING_TYPE, "NO" );
