DROP TABLE MCI_ONLINE_LOG CASCADE CONSTRAINTS;

DROP TABLE MCI_SCHEDULER CASCADE CONSTRAINTS;

DROP TABLE MCI_ERROR_LOG CASCADE CONSTRAINTS;

DROP TABLE MCI_FTP_LOG CASCADE CONSTRAINTS;

DROP TABLE MCI_MSG_INFOMATION CASCADE CONSTRAINTS; 

DROP TABLE MCI_MSG_MAPPING CASCADE CONSTRAINTS;


CREATE TABLE MCI_ONLINE_LOG
(
  ADAPTOR_NAME  VARCHAR2(30 BYTE)               NOT NULL,
  LOG_TIME      VARCHAR2(17 BYTE)               NOT NULL,
  TRAN_CODE     VARCHAR2(15 BYTE),
  COMM_TYPE     VARCHAR2(3 BYTE),
  COMM_OP       CHAR(1 BYTE),
  INOUT_FLAG    CHAR(1 BYTE),
  TRAN_SEQ      VARCHAR2(40 BYTE),
  TRAN_DATA     BLOB,
  STATUS        CHAR(1 BYTE),
  ERRMSG        VARCHAR2(200 BYTE)
);

COMMENT ON TABLE MCI_ONLINE_LOG IS 'MCI 온라인 로그';

COMMENT ON COLUMN MCI_ONLINE_LOG.STATUS IS '상태코드';

COMMENT ON COLUMN MCI_ONLINE_LOG.ERRMSG IS '오류메세지';

COMMENT ON COLUMN MCI_ONLINE_LOG.ADAPTOR_NAME IS '어댑터명';

COMMENT ON COLUMN MCI_ONLINE_LOG.LOG_TIME IS '로그시간 yyyymmddhh24missSSS';

COMMENT ON COLUMN MCI_ONLINE_LOG.COMM_TYPE IS '통신형태';

COMMENT ON COLUMN MCI_ONLINE_LOG.COMM_OP IS '통신 작업';

COMMENT ON COLUMN MCI_ONLINE_LOG.INOUT_FLAG IS '송수신구분';

COMMENT ON COLUMN MCI_ONLINE_LOG.TRAN_CODE IS '트랜잭션 코드';

COMMENT ON COLUMN MCI_ONLINE_LOG.TRAN_SEQ IS '트랜잭션 시퀀스';

COMMENT ON COLUMN MCI_ONLINE_LOG.TRAN_DATA IS '전문데이터';

CREATE INDEX IDX_LOG_TIME ON MCI_ONLINE_LOG
(LOG_TIME);




CREATE TABLE MCI_SCHEDULER
(
  SCHE_NAME     CHAR(25 BYTE)                   NOT NULL,
  CRONTAB       VARCHAR2(25 BYTE),
  ADAPTOR_NAME  VARCHAR2(30 BYTE),
  SCHE_DESC     VARCHAR2(100 BYTE),
  SCHE_FILE     VARCHAR2(50 BYTE),
  SCHE_DATE     VARCHAR2(20 BYTE),
  REPEAT        CHAR(1 BYTE),
  ACTIVE        VARCHAR2(3 BYTE),
  ETC           VARCHAR2(100 BYTE)
);

COMMENT ON TABLE MCI_SCHEDULER IS 'MCI 스케줄러 정보';

COMMENT ON COLUMN MCI_SCHEDULER.SCHE_NAME IS '스케줄명';

COMMENT ON COLUMN MCI_SCHEDULER.CRONTAB IS '기동시간';

COMMENT ON COLUMN MCI_SCHEDULER.ADAPTOR_NAME IS '어댑터명';

COMMENT ON COLUMN MCI_SCHEDULER.SCHE_DESC IS '설명';

COMMENT ON COLUMN MCI_SCHEDULER.SCHE_FILE IS '서비스명';

COMMENT ON COLUMN MCI_SCHEDULER.SCHE_DATE IS '스케줄주기';

COMMENT ON COLUMN MCI_SCHEDULER.REPEAT IS '반복여부';

COMMENT ON COLUMN MCI_SCHEDULER.ACTIVE IS '활성여부';

COMMENT ON COLUMN MCI_SCHEDULER.ETC IS 'etc';


ALTER TABLE MCI_SCHEDULER ADD (
  PRIMARY KEY
 (SCHE_NAME));
 
 
 
 CREATE TABLE MCI_ERROR_LOG
(
  ADAPTOR_NAME  VARCHAR2(30 BYTE)               NOT NULL,
  LOG_TIME      VARCHAR2(17 BYTE)               NOT NULL,
  COMM_TYPE     VARCHAR2(3 BYTE),
  COMM_OP       CHAR(1 BYTE),
  INOUT_FLAG    CHAR(1 BYTE),
  ERR_MSG       VARCHAR2(4000 BYTE)
);

COMMENT ON TABLE MCI_ERROR_LOG IS 'MCI 오류 로그';

COMMENT ON COLUMN MCI_ERROR_LOG.ADAPTOR_NAME IS '어댑터명';

COMMENT ON COLUMN MCI_ERROR_LOG.LOG_TIME IS '로그시간 yyyymmddhh24missSSS';

COMMENT ON COLUMN MCI_ERROR_LOG.COMM_TYPE IS '통신형태 JMS,TCP';

COMMENT ON COLUMN MCI_ERROR_LOG.COMM_OP IS '통신 작업 P(produce), C(consume), R(read), W(write)';

COMMENT ON COLUMN MCI_ERROR_LOG.INOUT_FLAG IS '송수신구분';

COMMENT ON COLUMN MCI_ERROR_LOG.ERR_MSG IS '에러 메시지';


CREATE INDEX IDX_ERR_LOG_TIME ON MCI_ERROR_LOG
(ADAPTOR_NAME, LOG_TIME);



CREATE TABLE MCI_FTP_LOG
(
  ADAPTOR_NAME  VARCHAR2(30 BYTE)               NOT NULL,
  TRAN_STIME    DATE,
  TRAN_ETIME    DATE,
  FILE_NAME     VARCHAR2(30 BYTE),
  TOTAL_SIZE    NUMBER,
  CUR_SIZE      NUMBER,
  TRAN_STATUS   CHAR(1 BYTE),
  INOUT_FLAG    CHAR(1 BYTE),
  ERROR_CODE    VARCHAR2(20 BYTE),
  ERROR_MSG     VARCHAR2(200 BYTE),
  STD_DATE      VARCHAR2(20 BYTE),
  TRAN_ID       VARCHAR2(30 BYTE),
  START_YN      CHAR(1 BYTE),
  FILE_PATH     VARCHAR2(100 BYTE)
);


COMMENT ON TABLE MCI_FTP_LOG IS 'MCI 일괄전송 로그';

COMMENT ON COLUMN MCI_FTP_LOG.ADAPTOR_NAME IS '어댑터명';

COMMENT ON COLUMN MCI_FTP_LOG.TRAN_STIME IS '전송시작시간';

COMMENT ON COLUMN MCI_FTP_LOG.TRAN_ETIME IS '전송종료시간';

COMMENT ON COLUMN MCI_FTP_LOG.FILE_NAME IS '파일명';

COMMENT ON COLUMN MCI_FTP_LOG.TOTAL_SIZE IS '총파일사이즈';

COMMENT ON COLUMN MCI_FTP_LOG.CUR_SIZE IS '현재받은사이즈';

COMMENT ON COLUMN MCI_FTP_LOG.TRAN_STATUS IS '전송상태';

COMMENT ON COLUMN MCI_FTP_LOG.INOUT_FLAG IS '송수신구분';

COMMENT ON COLUMN MCI_FTP_LOG.ERROR_CODE IS '에러코드';

COMMENT ON COLUMN MCI_FTP_LOG.ERROR_MSG IS '에러메세지';

COMMENT ON COLUMN MCI_FTP_LOG.STD_DATE IS '기준일자 yyyymmddhh24missSSS';

COMMENT ON COLUMN MCI_FTP_LOG.TRAN_ID IS '거래코드';

COMMENT ON COLUMN MCI_FTP_LOG.START_YN IS '재송신YN';

COMMENT ON COLUMN MCI_FTP_LOG.FILE_PATH IS '파일경로';


CREATE INDEX IDX_FTP_LOG_TIME ON MCI_FTP_LOG
(ADAPTOR_NAME, TRAN_STIME);


CREATE TABLE MCI_MSG_INFOMATION (
  AGENT_NAME          VARCHAR2(60)      NOT NULL, 
  TRAN_CODE           VARCHAR2(40)      NOT NULL, 
  TRAN_DIRECTION      CHAR(1)           NOT NULL, 
  TRAN_MODE           CHAR(1)           NOT NULL, 
  CHN_TRAN_CODE       VARCHAR2(40)          NULL, 
  REDIR_AGENT_NAME    VARCHAR2(60)      NOT NULL, 
  IN_TYPE             VARCHAR2(10)      NOT NULL, 
  OUT_TYPE            VARCHAR2(10)      NOT NULL, 
  SERVICE_NAME        VARCHAR2(20)          NULL, 
  TRAN_COMMENT        VARCHAR2(200)         NULL, 
  RESERVE             VARCHAR2(40)          NULL
);

COMMENT ON TABLE MCI_MSG_INFOMATION IS 'MCI 전문 정보';

COMMENT ON COLUMN MCI_MSG_INFOMATION.AGENT_NAME IS 'AGENT';

COMMENT ON COLUMN MCI_MSG_INFOMATION.TRAN_CODE IS '거래코드';

COMMENT ON COLUMN MCI_MSG_INFOMATION.TRAN_DIRECTION IS '송신방향(OUTBOUND(O),INBOUND(I))';

COMMENT ON COLUMN MCI_MSG_INFOMATION.TRAN_MODE IS '인터페이스(SYNC(S),ASYNC(A))';

COMMENT ON COLUMN MCI_MSG_INFOMATION.CHN_TRAN_CODE IS '변경할 거래코드';

COMMENT ON COLUMN MCI_MSG_INFOMATION.REDIR_AGENT_NAME IS '수신AGENT';

COMMENT ON COLUMN MCI_MSG_INFOMATION.IN_TYPE IS '입력 TYPE(NONE,XML,C-STR,MAP,BYTE[])';

COMMENT ON COLUMN MCI_MSG_INFOMATION.OUT_TYPE IS '출력 TYPE(NONE,XML,C-STR,MAP,BYTE[])';

COMMENT ON COLUMN MCI_MSG_INFOMATION.SERVICE_NAME IS '전문 수신후처리 호출 서비스명';

COMMENT ON COLUMN MCI_MSG_INFOMATION.TRAN_COMMENT IS '전문 설명';

ALTER TABLE MCI_MSG_INFOMATION ADD
(
    CONSTRAINT PK_MCI_MSG_INFOMATION
    PRIMARY KEY ( AGENT_NAME, TRAN_CODE, TRAN_DIRECTION, TRAN_MODE )
        USING INDEX
);

CREATE TABLE MCI_MSG_MAPPING (
  AGENT_NAME        VARCHAR2(60)      NOT NULL, 
  TRAN_CODE         VARCHAR2(40)      NOT NULL, 
  TRAN_DIRECTION    CHAR(1)           NOT NULL, 
  TRAN_MODE         CHAR(1)           NOT NULL, 
  MAPPING_TYPE      VARCHAR2(4)       NOT NULL, 
  NO                NUMBER(4)         NOT NULL, 
  DIVISION          CHAR(1)               NULL, 
  NAME_KOR          VARCHAR2(60)          NULL, 
  NAME              VARCHAR2(60)          NULL, 
  RANK              VARCHAR2(20)          NULL, 
  TYPE              VARCHAR2(10)          NULL, 
  LENGTH            NUMBER(4)        DEFAULT 0             NULL, 
  CHILD_COUNT       NUMBER(4)        DEFAULT 0             NULL, 
  COUNT_NO          NUMBER(4)        DEFAULT 0             NULL, 
  REQURED           CHAR(1)          DEFAULT 'N'               NULL, 
  FUNCTION          VARCHAR2(100)         NULL, 
  DEFAULT_VAL       VARCHAR2(100)         NULL
);


COMMENT ON TABLE MCI_MSG_MAPPING IS '전문 맵핑 필드 정보';

COMMENT ON COLUMN MCI_MSG_MAPPING.AGENT_NAME IS 'AGENT명';

COMMENT ON COLUMN MCI_MSG_MAPPING.TRAN_CODE IS '거래코드';

COMMENT ON COLUMN MCI_MSG_MAPPING.TRAN_DIRECTION IS '송신방향(OUTBOUND(O),INBOUND(I))';

COMMENT ON COLUMN MCI_MSG_MAPPING.TRAN_MODE IS '인터페이스(SYNC(S),ASYNC(A))';

COMMENT ON COLUMN MCI_MSG_MAPPING.MAPPING_TYPE IS 'INPUT,OUTPUT구분';

COMMENT ON COLUMN MCI_MSG_MAPPING.NO IS '등록순번';

COMMENT ON COLUMN MCI_MSG_MAPPING.DIVISION IS '구분(HEADER(H),DATA(D))';

COMMENT ON COLUMN MCI_MSG_MAPPING.NAME_KOR IS '항목명(한글)';

COMMENT ON COLUMN MCI_MSG_MAPPING.NAME IS '필드명(영어)';

COMMENT ON COLUMN MCI_MSG_MAPPING.RANK IS '변환순번';

COMMENT ON COLUMN MCI_MSG_MAPPING.TYPE IS '타입';

COMMENT ON COLUMN MCI_MSG_MAPPING.LENGTH IS '전문 길이 , LIST는 최대 반복 횟수';

COMMENT ON COLUMN MCI_MSG_MAPPING.CHILD_COUNT IS '하위 필드수';

COMMENT ON COLUMN MCI_MSG_MAPPING.COUNT_NO IS '카운트 넘버 Index No';

COMMENT ON COLUMN MCI_MSG_MAPPING.REQURED IS '필수유무 Y,N';

COMMENT ON COLUMN MCI_MSG_MAPPING.FUNCTION IS 'FUNCTION';

COMMENT ON COLUMN MCI_MSG_MAPPING.DEFAULT_VAL IS '기본값(전문테스트용)';

ALTER TABLE MCI_MSG_MAPPING ADD
(
    CONSTRAINT PK_MCI_MSG_MAPPING_RECORD
    PRIMARY KEY ( AGENT_NAME, TRAN_CODE, TRAN_DIRECTION, TRAN_MODE, MAPPING_TYPE, NO )
        USING INDEX
);


