/* ESB_TEMP_IF_MASTER_LOG 테이블 생성 */
CREATE TABLE ESB_TEMP_IF_MASTER_LOG (
  IF_ID VARCHAR(40) NOT NULL,
  TX_ID VARCHAR(64) NOT NULL,
  TX_COUNT INT(8),
  TX_PROPERTY VARCHAR(4000),
  TX_START_DATE VARCHAR(17),
  TX_HUB_RCV_DATE VARCHAR(17),
  ESB_HOST VARCHAR(255),
  SND_SYSTEM VARCHAR(100),
  RCV_SYSTEM VARCHAR(100),
  PRIMARY KEY (TX_ID)
);

/* ESB_TEMP_IF_MASTER_LOG 테이블 인덱스 추가 */
CREATE INDEX IDX_ESB_TEMP_IF_MASTER_LOG_TX_START_DATE ON ESB_TEMP_IF_MASTER_LOG(TX_START_DATE);
CREATE INDEX IDX_ESB_TEMP_IF_MASTER_LOG_TX_HUB_RCV_DATE ON ESB_TEMP_IF_MASTER_LOG(TX_HUB_RCV_DATE);

/* ESB_TEMP_IF_DEST_LOG 테이블 생성 */

CREATE TABLE ESB_TEMP_IF_DEST_LOG (
  TX_ID VARCHAR(64) NOT NULL,
  DEST_ID VARCHAR(64) NOT NULL,
  DEST_RCV_DATE VARCHAR(17),
  DEST_RESULT CHAR(1),
  RESULT_MESSAGE VARCHAR(4000),
  REACTION_CNT INT(4),
  REACTION_DATE VARCHAR(17),
  DEST_ERROR_COUNT INT(8),
  SEND_MESSAGE VARCHAR(4000),
  PRIMARY KEY (TX_ID,DEST_ID)
);

/* ESB_TEMP_IF_DEST_LOG 테이블 인덱스 추가 */
CREATE INDEX IDX_ESB_TEMP_IF_DEST_LOG_DEST_RESULT ON ESB_TEMP_IF_DEST_LOG(DEST_RESULT);
CREATE INDEX IDX_ESB_TEMP_IF_DEST_LOG_DEST_RCV_DATE ON ESB_TEMP_IF_DEST_LOG(DEST_RCV_DATE);

/* INDIGO_MESSAGETRACED 테이블 생성 */
CREATE TABLE INDIGO_MESSAGETRACED (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  PROPERTIES VARCHAR(255),
  TIME_STAMP TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  HEADERS VARCHAR(2000),
  EXCHANGEID VARCHAR(255),
  BODY VARCHAR(4000),
  EXCHANGEPATTERN VARCHAR(150),
  ROUTEID VARCHAR(200),
  FROMENDPOINTURI VARCHAR(255),
  PREVIOUSNODE VARCHAR(255),
  TONODE VARCHAR(255),
  SHORTEXCHANGEID VARCHAR(150),
  BODYTYPE VARCHAR(150),
  OUTBODY VARCHAR(4000),
  OUTBODYTYPE VARCHAR(150),
  OUTHEADERS VARCHAR(2000),
  CAUSEDBYEXCEPTION VARCHAR(2000),
  IN_OUT VARCHAR(3),
  STATUS CHAR(1),
  NODEID VARCHAR(255),
  GROUPEXCHANGEID VARCHAR(150),
  TX_ID VARCHAR(100),
  RETRY_COUNT INT(11),
  PREVIOUSNODEID VARCHAR(20),
  PRIMARY KEY (ID)
);

CREATE INDEX IDX_INDIGO_MESSAGETRACED_TX_ID ON INDIGO_MESSAGETRACED(TX_ID);
CREATE INDEX IDX_INDIGO_MESSAGETRACED_GROUPEXCHANGEID ON INDIGO_MESSAGETRACED(GROUPEXCHANGEID);